In [2]:
import numpy as np

In [3]:
# checking for missing values

In [4]:
lending_co_data_numeric = np.loadtxt(r"C:\Users\97798\Desktop\1.2 Lending-company-Numeric.csv",delimiter = ',')

In [5]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [6]:
# # np.isnan()

# returns an array with the same shape and size as the one we input

# true- missing value
# false- no missing value

In [7]:
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [9]:
# boolean values

# true - 1
# false - 0

# if we add up all the individual values the sum should equal the total number of missing values in the original dataset


In [10]:

# no missing data point
np.isnan(lending_co_data_numeric).sum()

0

In [30]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.4 Lending-company-Numeric-NAN.csv",delimiter=';',
                                      )

In [31]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [32]:
np.isnan(lending_co_data_numeric_NAN)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [33]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [34]:
np.array_equal(lending_co_data_numeric,lending_co_data_numeric_NAN)

False

In [35]:
temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) + 1

In [36]:
temporary_fill

64002.0

In [37]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.4 Lending-company-Numeric-NAN.csv",delimiter=';',
                                   filling_values= temporary_fill   )

In [38]:
lending_co_data_numeric_NAN

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]])

In [39]:
np.isnan(lending_co_data_numeric_NAN).sum()

0