In [1]:
import numpy as np

In [45]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';')

In [46]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [48]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [49]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';',
                                           filling_values= temporary_fill)

In [62]:
for i in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(
    lending_co_data_numeric_NAN[:,i] == temporary_fill,
    temporary_mean[i],
    lending_co_data_numeric_NAN[:,i]
)

lending_co_data_numeric_NAN    
    

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2315.87,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [63]:
# np.coicatenate(): linking together objects in a chain
    
#     creating a new larger array by merging existing smaller arrays in 

In [64]:
lending_co_data_numeric_NAN[0,:]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

In [66]:
lending_co_data_numeric_NAN[1,:]

array([ 2000.,    40.,   365.,  3061.,  4171., 15041.])

In [68]:
np.concatenate((lending_co_data_numeric_NAN[0,:],lending_co_data_numeric_NAN[1,:]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [73]:
np.concatenate((lending_co_data_numeric_NAN,lending_co_data_numeric_NAN),axis =1 )

array([[ 2000.  ,    40.  ,   365.  , ...,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  , ...,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  , ...,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2315.87,    40.  ,   365.  , ...,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  , ...,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  , ...,  4601.  ,  4601.  , 16600.  ]])

In [74]:
np.concatenate((lending_co_data_numeric_NAN,lending_co_data_numeric_NAN),axis =1 ).shape

(1043, 12)

In [75]:
lending_co_data_numeric_NAN.shape

(1043, 6)

In [76]:
array_example_1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [77]:
array_example_2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]]])

In [78]:
array_example_1.shape

(1, 4, 4)

In [79]:
array_example_2.shape

(1, 4, 4)

In [80]:
np.concatenate((array_example_1,array_example_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]]])

In [81]:
np.vstack((array_example_1,array_example_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]]])

In [82]:
np.hstack((array_example_1,array_example_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]]])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)