In [66]:
import numpy as np

In [67]:
lending_co_data_numeric = np.loadtxt(r"C:\Users\97798\Desktop\manipulation of data\1.2 Lending-company-Numeric.csv",delimiter=',')

In [87]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [90]:

np.delete(lending_co_data_numeric,0).shape

(6257,)

In [91]:
lending_co_data_numeric.size

6258

In [92]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [95]:
# remove entire row 

np.delete(lending_co_data_numeric,0,axis = 0)

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [96]:
# remove first column
np.delete(lending_co_data_numeric,0,axis = 1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [97]:
np.delete(lending_co_data_numeric,(1,3,5),axis = 1)

array([[2000.,  365., 4241.],
       [2000.,  365., 4171.],
       [1000.,  365., 3280.],
       ...,
       [2000.,  365., 5001.],
       [1000.,  365., 3320.],
       [2000.,  365., 4601.]])

In [98]:
# remove both row and columns simaltaneously

np.delete(np.delete(lending_co_data_numeric,(1,3,5),axis = 1),[0,2,-1],axis=0)

array([[2000.,  365., 4171.],
       [2000.,  365., 4241.],
       [2000.,  365., 4820.],
       ...,
       [2000.,  365., 5440.],
       [2000.,  365., 5001.],
       [1000.,  365., 3320.]])