In [66]:
import numpy as np

In [177]:
lending_co_data_numeric = np.loadtxt(r"C:\Users\97798\Desktop\manipulation of data\1.2 Lending-company-Numeric.csv",delimiter=',')[:8]

In [178]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [172]:
# # shuffling: rearranging the parts of a dataset

# entire rows of data gets moved up or down the dataset

In [181]:
np.random.shuffle(lending_co_data_numeric)

In [182]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [183]:
np.random.shuffle(lending_co_data_numeric)

In [184]:
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.]])

In [185]:
lending_co_data_numeric = np.loadtxt(r"C:\Users\97798\Desktop\manipulation of data\1.2 Lending-company-Numeric.csv",delimiter=',')

In [186]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [187]:
from numpy.random import shuffle

In [188]:
shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 4000.,    50.,   365.,  5350.,  6500., 14400.],
       [ 2000.,    40.,   365.,  3401.,  5851., 16600.],
       [ 2000.,    40.,   365.,  3280.,  4400., 16290.],
       ...,
       [ 4000.,    50.,   365.,  5550.,  7300., 22250.],
       [ 2000.,    50.,   365.,  4150.,  5250., 20250.],
       [ 2000.,    40.,   365.,  3201.,  4331., 16311.]])

In [189]:
# random generators: generate data, shuffle data

In [190]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [199]:
array_RG = gen(pcg(seed=365))
array_RG.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  2991.,  4281., 16600.],
       [ 2000.,    40.,   365.,  4701.,  6201., 14401.],
       [ 4000.,    50.,   365.,  5750.,  7450., 22250.],
       ...,
       [ 2000.,    40.,   365.,  3261.,  4601., 15781.],
       [ 1000.,    40.,   365.,  2120.,  3440., 15600.],
       [ 2000.,    50.,   365.,  4000.,  5400., 20250.]])