In [1]:
import numpy as np

In [8]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';')

In [9]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [10]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [15]:
temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2)+1
temporary_mean = np.nanmean(lending_co_data_numeric_NAN,axis =0).round(2)

lending_co_data_numeric_NAN = np.genfromtxt(
    r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",
    delimiter=';',
    filling_values=temporary_fill
)

for i in range (lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(lending_co_data_numeric_NAN[:,i] == temporary_fill,
                                                temporary_mean[i],
                                                lending_co_data_numeric_NAN[:,i])
        
        
    
    
lending_co_data_numeric_NAN    

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2315.87,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [16]:
# stacking: placing multiple objects on top of one another to create a bigger object

In [18]:
np.stack((lending_co_data_numeric_NAN[:,0],lending_co_data_numeric_NAN[:,1]))

array([[2000.  , 2000.  , 1000.  , ..., 2315.87, 1000.  , 2000.  ],
       [  40.  ,   40.  ,   40.  , ...,   40.  ,   40.  ,   40.  ]])

In [20]:
np.stack((lending_co_data_numeric_NAN[:,1],lending_co_data_numeric_NAN[:,0]))

array([[  40.  ,   40.  ,   40.  , ...,   40.  ,   40.  ,   40.  ],
       [2000.  , 2000.  , 1000.  , ..., 2315.87, 1000.  , 2000.  ]])

In [21]:
np.stack((lending_co_data_numeric_NAN[:,1],lending_co_data_numeric_NAN[:,0]),axis=1)

array([[  40.  , 2000.  ],
       [  40.  , 2000.  ],
       [  40.  , 1000.  ],
       ...,
       [  40.  , 2315.87],
       [  40.  , 1000.  ],
       [  40.  , 2000.  ]])

In [22]:
np.stack((lending_co_data_numeric_NAN[:,1],lending_co_data_numeric_NAN[:,0],lending_co_data_numeric_NAN[:,2]),axis=1)

array([[  40.  , 2000.  ,  365.  ],
       [  40.  , 2000.  ,  365.  ],
       [  40.  , 1000.  ,  365.  ],
       ...,
       [  40.  , 2315.87,  365.  ],
       [  40.  , 1000.  ,  365.  ],
       [  40.  , 2000.  ,  365.  ]])

In [23]:
lending_co_data_numeric_NAN.shape

(1043, 6)

In [27]:
# vertical stack
np.vstack((lending_co_data_numeric_NAN[:,0],lending_co_data_numeric_NAN[:,1])).shape

(2, 1043)

In [29]:
np.hstack((lending_co_data_numeric_NAN,lending_co_data_numeric_NAN)).shape

(1043, 12)

In [30]:
# dstack: we stack arrays in third dimension

In [36]:
np.dstack((lending_co_data_numeric_NAN,lending_co_data_numeric_NAN))

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2315.87,  2315.87],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

In [37]:
array_example_1 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])

In [38]:
array_example_2 = array_example_1 * 2

In [42]:
array_example_1.shape

(1, 4, 4)

In [41]:
array_example_2.shape

(1, 4, 4)

In [44]:
np.dstack((array_example_1,array_example_2)).shape

(1, 4, 8)