In [40]:
import numpy as np

In [42]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';')

In [43]:
 lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [44]:
# find means along each column

temporary_mean = np.nanmean(lending_co_data_numeric_NAN,axis=0).round(2)

In [46]:
 temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [47]:
filler_value = np.nanmean(lending_co_data_numeric_NAN).round(2)+1

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';',
                                           filling_values=filler_value)

In [48]:
lending_co_data_numeric_NAN

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 4759.21,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [49]:
filler_value

4759.21

In [50]:
np.mean(lending_co_data_numeric_NAN[:,0]).round(2)

2332.04

In [52]:
temporary_mean[0]

2250.25

In [53]:
# where function


In [56]:
lending_co_data_numeric_NAN[:,0] = np.where(
    lending_co_data_numeric_NAN[:,0] == filler_value,
    temporary_mean[0],
    lending_co_data_numeric_NAN[:,0]
)

In [57]:
lending_co_data_numeric_NAN[:,0]

array([2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ])

In [58]:
np.mean(lending_co_data_numeric_NAN[:,0]).round(2)

2250.25

In [60]:
np.mean(lending_co_data_numeric_NAN[:,0]).round(2)

2250.25

In [61]:
# to fill nan for all columns

for i in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(
    lending_co_data_numeric_NAN[:,i] == filler_value,
    temporary_mean[i],
    lending_co_data_numeric_NAN[:,i]
)
    

In [63]:
lending_co_data_numeric_NAN

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [64]:
# to fill nan for all columns

for i in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(
    lending_co_data_numeric_NAN[:,i]<0,
    0,
    lending_co_data_numeric_NAN[:,i]
)
    

In [65]:
lending_co_data_numeric_NAN

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])