In [1]:
import numpy as np

In [45]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';')

In [46]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [48]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [49]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\manipulation of data\1.4 Lending-company-Numeric-NAN.csv",delimiter=';',
                                           filling_values= temporary_fill)

In [85]:
for i in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(
    lending_co_data_numeric_NAN[:,i] == temporary_fill,
    temporary_mean[i],
    lending_co_data_numeric_NAN[:,i]
)

lending_co_data_numeric_NAN    
    

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2315.87,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [86]:
# np.unique():
#     takes an array as an input and creates another array that contains all the different values from the first one

In [87]:
np.unique(lending_co_data_numeric_NAN)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.])

In [88]:
np.unique(lending_co_data_numeric_NAN).shape

(1125,)

In [89]:
np.unique(lending_co_data_numeric_NAN[:,1])

array([ 35.  ,  40.  ,  50.  , 125.  , 165.  , 181.56])

In [90]:
array_example = np.array(["a","b","c","d","A","B","C","D"])

In [92]:
array_example.shape

(8,)

In [94]:
# strings sorting

np.unique(array_example)

array(['A', 'B', 'C', 'D', 'a', 'b', 'c', 'd'], dtype='<U1')

In [95]:
# also find unique counts of data

np.unique(lending_co_data_numeric_NAN[:,1],return_counts=True)

(array([ 35.  ,  40.  ,  50.  , 125.  , 165.  , 181.56]),
 array([  3, 541, 431,  18,   2,  48], dtype=int64))

In [96]:
# find index also

np.unique(lending_co_data_numeric_NAN[:,1],return_counts=True, return_index=True)

(array([ 35.  ,  40.  ,  50.  , 125.  , 165.  , 181.56]),
 array([327,   0,   4,  19,  27, 152], dtype=int64),
 array([  3, 541, 431,  18,   2,  48], dtype=int64))