In [1]:
import numpy as np

In [2]:
# importing the dataset

In [3]:
np.set_printoptions(suppress=True,linewidth=100, precision =2)

In [4]:
raw_data_np = np.genfromtxt(r"C:\Users\97798\Desktop\1.2 loan-data.csv", delimiter=';', encoding='Windows-1252',
                           skip_header=1,
                           autostrip=True)


In [5]:
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [6]:
# check for missing value

In [7]:
np.isnan(raw_data_np).sum()

88005

In [8]:
temporary_fill = np.nanmax(raw_data_np)+1
temporary_mean = np.nanmean(raw_data_np,axis=0)

C:\Users\97798\AppData\Local\Temp\ipykernel_11928\2154036395.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np,axis=0)


In [9]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
temporary_fill

68616520.0

In [11]:
temprary_stats = np.array([np.nanmin(raw_data_np,axis=0),
                          temporary_mean,
                           np.nanmax(raw_data_np,axis=0)
                          ])

C:\Users\97798\AppData\Local\Temp\ipykernel_11928\3047036152.py:1: RuntimeWarning: All-NaN slice encountered
  temprary_stats = np.array([np.nanmin(raw_data_np,axis=0),
C:\Users\97798\AppData\Local\Temp\ipykernel_11928\3047036152.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)


In [12]:
temprary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [13]:
# splitting the dataset into numeric and string datasset








In [14]:
column_strings = np.argwhere(np.isnan(temporary_mean))

In [15]:
column_strings.squeeze()


array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [16]:
column_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()

In [17]:
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [18]:
# reimporting the datset
column_strings

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

In [19]:
loan_data_strings = np.genfromtxt(r"C:\Users\97798\Desktop\1.2 loan-data.csv", delimiter=';', encoding='Windows-1252',
                                  skip_header=1,
                                  autostrip=True,
                                  usecols= column_strings.squeeze(),
                                  dtype = np.str_
                                
                                 )


In [20]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [21]:
loan_data_numeric = np.genfromtxt(r"C:\Users\97798\Desktop\1.2 loan-data.csv", delimiter=';', encoding='Windows-1252',
                                  skip_header=1,
                                  autostrip=True,
                                  usecols= column_numeric,
                                  filling_values= temporary_fill
                                 
                                
                                 )

In [22]:
loan_data_numeric.shape

(10000, 6)

In [23]:
header_full = np.genfromtxt(r"C:\Users\97798\Desktop\1.2 loan-data.csv", delimiter=';', encoding='Windows-1252',
                                  
                                  autostrip=True,
                                
                                  dtype = np.str_,
                                skip_footer = raw_data_np.shape[0]
                                
                                 )

In [24]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [25]:
header_strings, header_numeric = header_full[column_strings],header_full[column_numeric]

In [26]:
header_strings.squeeze()

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
header_numeric.squeeze()

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [28]:
# setting up checkpoints
def checkpoint(file_name, checkpoint_header,checkpoint_data):
    np.savez(file_name,header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file = file_name + ".npz")
    return checkpoint_variable

checkpoint_test = checkpoint("Checkpoint-test", header_strings, loan_data_strings)


In [29]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [30]:
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

In [31]:
# manipulating strings columns of original dataset

In [32]:
header_strings


array([['issue_d'],
       ['loan_status'],
       ['term'],
       ['grade'],
       ['sub_grade'],
       ['verification_status'],
       ['url'],
       ['addr_state']], dtype='<U19')

In [33]:
header_strings[0] ="issue date"

In [34]:
header_strings

array([['issue date'],
       ['loan_status'],
       ['term'],
       ['grade'],
       ['sub_grade'],
       ['verification_status'],
       ['url'],
       ['addr_state']], dtype='<U19')

In [35]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [36]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")

In [37]:
np.unique(loan_data_strings[:,0])


array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [38]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [39]:
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [40]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      i,
                                      loan_data_strings[:,0])
                                     

In [41]:
loan_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [42]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [43]:
# loan status

In [44]:
header_strings

array([['issue date'],
       ['loan_status'],
       ['term'],
       ['grade'],
       ['sub_grade'],
       ['verification_status'],
       ['url'],
       ['addr_state']], dtype='<U19')

In [45]:
header_strings[1]

array(['loan_status'], dtype='<U19')

In [46]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [47]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [48]:
status_bad

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [49]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [50]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [51]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [52]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2]," months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [53]:
header_strings[2] = "term_months"
header_strings

array([['issue date'],
       ['loan_status'],
       ['term_months'],
       ['grade'],
       ['sub_grade'],
       ['verification_status'],
       ['url'],
       ['addr_state']], dtype='<U19')

In [54]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',
                                 loan_data_strings[:,2])

In [55]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [56]:
# grade and sub grade

In [57]:
header_strings

array([['issue date'],
       ['loan_status'],
       ['term_months'],
       ['grade'],
       ['sub_grade'],
       ['verification_status'],
       ['url'],
       ['addr_state']], dtype='<U19')

In [58]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [59]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [60]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                       loan_data_strings[:,4])
        
  

In [61]:
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [62]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                 'H1',
                                 loan_data_strings[:,4])

In [63]:
np.unique(loan_data_strings[:,4
                 ])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [64]:
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [65]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [66]:
header_strings = np.delete(header_strings,3)

In [67]:
header_strings[3]

'sub_grade'

In [68]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [69]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))

In [70]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [71]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])
                                     

In [72]:
np.unique(loan_data_strings[:,3]).size

36

In [73]:
# verification status

In [74]:
header_strings

array(['issue date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [75]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [76]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '')|(loan_data_strings[:,4] == 'Not Verified'),0,1)

In [77]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [78]:
# urls

In [79]:
header_strings[5]

'url'

In [80]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [81]:
np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [82]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [83]:
loan_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [84]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [85]:
loan_data_numeric[:,0].astype(dtype =np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [86]:
np.array_equal(loan_data_strings[:,5].astype(dtype = np.int32),loan_data_numeric[:,0].astype(dtype =np.int32))

True

In [87]:
loan_data_strings = np.delete(loan_data_strings,5,axis = 1)
header_strings = np.delete(header_strings,5)

In [88]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [89]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [90]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [91]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [92]:
header_strings[5] = "state_address"

In [93]:

np.sort(np.unique(loan_data_strings[:,5],return_counts=True))

array([['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'],
       ['10', '107', '108', '116', '119', '130', '1336', '143', '143', '148', '152', '156', '16',
        '160', '17', '201', '210', '216', '220', '222', '24', '242', '25', '26', '261', '267',
        '27', '27', '27', '28', '312', '320', '321', '341', '389', '40', '44', '49', '500', '57',
        '58', '61', '690', '74', '74', '758', '777', '83', '84', '84']], dtype='<U69')

In [94]:
state_names , state_counts = np.unique(loan_data_strings[:,5],return_counts=True)
state_count_sorted = np.argsort(-state_counts)

In [95]:
state_names[state_count_sorted],state_counts[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [96]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] =='',
                                 0,
                                 loan_data_strings[:,5])
    

In [97]:
west = ['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'AK', 'HI']
midwest = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'MI', 'IN', 'OH']
south = ['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'GA', 'FL', 'SC', 'NC', 'VA', 'WV', 'MD', 'DC', 'DE']
east = ['PA', 'NY', 'NJ', 'CT', 'RI', 'MA', 'VT', 'NH', 'ME']



In [98]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],west),1,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],south),2,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],east),4,loan_data_strings[:,5])


In [99]:
np.unique(loan_data_strings[:,5]).size

5

In [100]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [101]:

loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [102]:
# convert to numbers

In [103]:
loan_data_strings.astype(dtype = np.int32)
                       

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [104]:
loan_data_strings = loan_data_strings.astype(dtype = np.int32)


In [105]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [106]:
# checkpoint 1: Strings

In [107]:
checkpoint("checkpoints-strings",header_strings,loan_data_strings)

In [108]:
checkpoint_strings = checkpoint("checkpoints-strings",header_strings,loan_data_strings)

In [109]:
checkpoint_strings['header']

array(['issue date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [110]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [111]:
np.array_equal(loan_data_strings,checkpoint_strings['data'])

True

In [112]:
# Manipulating numbers

In [113]:
loan_data_numeric.shape

(10000, 6)

In [114]:
np.isnan(loan_data_numeric).sum()

0

In [115]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [116]:
temporary_fill 

68616520.0

In [117]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [118]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [119]:
temprary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [120]:
temprary_stats[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [121]:
# funded amount: replace with minimum values

In [122]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] ==  temporary_fill,
                                  temprary_stats[0,column_numeric[2]],
                                  loan_data_numeric[:,2]
                                 )

In [123]:
loan_data_numeric[:,2]
loan_data_numeric.shape

(10000, 6)

In [124]:
# loaned amount, interest rate, total payment, installment

In [125]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [126]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] ==  temporary_fill,
                                      temprary_stats[0,column_numeric[i]],
                                      loan_data_numeric[:,i]
                                     )

In [127]:
loan_data_numeric.shape

(10000, 6)

In [128]:
# currency change

In [129]:
eur_usd = np.genfromtxt(
    r"C:\Users\97798\Desktop\1.3 EUR-USD.csv",
    delimiter=',',
    autostrip=True,
    skip_header=1,
    usecols=3
)

In [130]:
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [131]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(
        exchange_rate == i,
        eur_usd[i-1],
        exchange_rate
    )
    
exchange_rate = np.where(
    exchange_rate == 0,
    np.mean(eur_usd),
    exchange_rate
    )    

In [132]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [133]:
exchange_rate.shape

(10000,)

In [134]:
loan_data_numeric.shape

(10000, 6)

In [135]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [136]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [137]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))


In [138]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [139]:
cols_dollar = np.array([1,2,4,5])

In [140]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [141]:
for i in cols_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))

In [142]:
loan_data_numeric.shape

(10000, 11)

In [143]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[cols_dollar]])

In [144]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [145]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [146]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [147]:
header_numeric[cols_dollar]=np.array([column_name + '_USD' for column_name in header_numeric[cols_dollar]])

In [148]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [149]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [150]:
header_numeric = header_numeric[columns_index_order]

In [151]:
header_numeric


array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [152]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]

In [153]:
loan_data_numeric.shape

(10000, 11)

In [154]:
# intrest rate

In [155]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [156]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [159]:
loan_data_numeric.shape

(10000, 11)

In [184]:
loan_data_strings.shape

checkpoint_numeric = checkpoint('Checkpoint-Numeric',header_numeric,loan_data_numeric)

In [185]:
checkpoint_numeric['header'],checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,     1000.  ,      899.74, ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [186]:
checkpoint_strings['data'].shape

(10000, 6)

In [187]:
checkpoint_numeric['data'].shape

(10000, 11)

In [189]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))

In [190]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,     1000.  ,      899.74, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [192]:
type(loan_data)

numpy.ndarray

In [169]:
# sorting the data set

In [194]:
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))

In [195]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [199]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [201]:
loan_data = np.vstack((header_full,loan_data))

In [202]:
np.savetxt("loan-data-preprocessed.csv",
           loan_data,
           fmt = '%s',
           delimiter=','
          )