In [64]:
import numpy as np

In [65]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [70]:
# np.median()

# the middle value of a sorted dataset

In [72]:
np.sort(matrix_A,axis=None
       )

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [73]:
np.median(matrix_A)

3.0

In [74]:
np.mean(matrix_A)

3.4

In [75]:
# average: computes the average, weighted matrix

In [76]:
np.average(matrix_A)

3.4

In [77]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(365))

array_weights = array_RG.random(size=(3,5))
array_weights

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736]])

In [78]:
np.average(matrix_A, weights= array_weights)

3.2120290871899306

In [80]:
np.mean(matrix_A)

3.4

In [81]:
# np.var()


In [82]:
np.var(matrix_A)

7.84

In [83]:
# np.std()

np.std(matrix_A)

2.8

In [85]:
2.8*2.8

7.839999999999999