In [64]:
import numpy as np

In [86]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [87]:
# covarience

In [88]:
np.cov(matrix_A)

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [90]:
# correlation
# finds the relationships between every two rows of the array
np.corrcoef(matrix_A)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])