In [23]:
import numpy as np

In [24]:
# maximal and minimal values in array

In [25]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [26]:
np.min(matrix_A)

0

In [27]:
np.min(matrix_A[0])

0

In [28]:
np.amin(matrix_A)

0

In [29]:
# min va amin 
# are alias to each other

In [30]:
# np.minimum()

# requires at least 2 input arrays

# generates an array which holds the elementwise minimal values

# compares the values at the same position in each of the arrays before taking the lowest one

In [31]:
np.minimum(matrix_A[0],matrix_A[2])

array([1, 0, 0, 3, 0])

In [32]:
matrix_A[0]

array([1, 0, 0, 3, 1])

In [33]:
matrix_A[2]

array([4, 5, 3, 8, 0])

In [35]:
# reduce shows the lowest value along the column side
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [36]:
# maximum equivalents: max, amax, maximum