In [1]:
import numpy as np

In [17]:
# np.mean()

In [3]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])

In [4]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
np.mean(matrix_A)

3.4

In [7]:
print("Mean is {}".format(np.mean(matrix_A)))

Mean is 3.4


In [8]:
np.mean(matrix_A[0])

1.0

In [11]:
np.mean(matrix_A[:,0
                ])

2.6666666666666665

In [13]:
matrix_A[:,0]

array([1, 3, 4])

In [15]:
# find out means for every column
np.mean(matrix_A,axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [16]:
# find out means for every row
np.mean(matrix_A,axis=1)

array([1. , 5.2, 4. ])

In [19]:
matrix_A.mean()

3.4

In [21]:
# square root
np.sqrt(matrix_A)

array([[1.        , 0.        , 0.        , 1.73205081, 1.        ],
       [1.73205081, 2.44948974, 2.44948974, 1.41421356, 3.        ],
       [2.        , 2.23606798, 1.73205081, 2.82842712, 0.        ]])

In [22]:
np.mean(matrix_A,axis=1,dtype=np.float32)

array([1. , 5.2, 4. ], dtype=float32)