In [37]:
import numpy as np

In [38]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [45]:
# # np.ptp()

# returns the difference between the highest and lowest within the matrix

In [41]:
np.ptp(matrix_A)

9

In [42]:
np.ptp(matrix_A, axis =0)

array([3, 6, 6, 6, 9])

In [43]:
np.ptp(matrix_A, axis =1 )

array([3, 7, 8])

In [47]:
# # # np.percentile()

# # returns a specific percentile of a given set 

# # requires a second input the percentile

# a value that is greater than the corresponding % of the dataset, the 70th percentile is greater than 70% of the data

In [48]:
np.sort(matrix_A,axis=None)


array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [55]:
np.percentile(matrix_A,70,method="higher")

5

In [56]:
np.percentile(matrix_A,70,method="midpoint")

4.5

In [57]:
np.percentile(matrix_A,70,method="nearest")

5

In [58]:
# 50 gives the median value

np.percentile(matrix_A,50)

3.0

In [60]:
# # quantile 

# a value that is greayte than the corresponding part of the dataset

# 70 th percentile = 0.7 quantile

In [63]:
np.quantile(matrix_A,0.7,method='nearest')

5