In [121]:
import numpy as np


In [122]:
np.set_printoptions(suppress = True, linewidth = 150, precision = 2)

In [123]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [124]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [125]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [126]:
# ### 2. For each of the 3 arrays we defined above, do the following:
#     A) Call the np.max() or np.amax() function and plug in the array as an input. 
#     B) Call the np.max() or np.amax() function along an axis of your choice and plug in the array as an input.
#     C) Call the np.maximum.reduce() function and plug in the array as an input. 


In [129]:
np.max(array_1D)

14

In [130]:
np.amax(array_1D)

14

In [131]:
np.max(array_2D)
np.amax(array_2D)

87

In [133]:
np.max(array_3D)
np.amax(array_3D)

54

In [135]:
np.max(array_1D,axis=0)


14

In [137]:
np.max(array_2D,axis=0)
np.max(array_2D,axis=1)

array([60, 87, 55])

In [138]:
np.max(array_3D,axis=0)
np.max(array_3D,axis=1)

array([[11, 21, 31, 41, 51],
       [51, 52, 53, 54, 15]])

In [140]:
np.maximum.reduce(array_1D)

14

In [141]:
### 3. For each array find the difference between its maximum and minimum. 

In [142]:
difference = np.max(array_1D)- np.min(array_1D)

In [143]:
np.ptp(array_1D)

4

In [144]:
difference

4

In [145]:
difference = np.max(array_2D)- np.min(array_2D)
np.ptp(array_2D)

76

In [146]:
difference

76

In [147]:
### 4. For the 2-D and 3-D arrays find the difference between the maximum and minimum, for every row.

In [154]:
np.max(array_2D,axis=1) - np.min(array_2D,axis =1)

array([40, 44, 44])

In [155]:
np.max(array_3D,axis=1) - np.min(array_3D,axis =1)

array([[10, 19, 28, 37, 46],
       [40, 40, 40, 40, 10]])

In [156]:
# ### 5. For all 3 arrays we defined, use the<i> np.percentile() </i>and <i>np.quantile()</i> functions to find the following: 
#     A) The 30-th percentile (or 0.3-th quantile). 
#     B) The 66-th percentile (or 0.66-th qunatile). 
#     C) The median. 
#    (<b>Hint</b>: The median value is equivalent to the 50-th percentile)

In [158]:
np.percentile(array_1D,30)
np.quantile(array_1D,0.3)

11.2

In [159]:
np.percentile(array_3D,50)

13.5

In [160]:
np.sort(array_1D)


array([10, 11, 12, 13, 14])

In [161]:
np.sort(array_2D, axis = None)


array([11, 20, 22, 30, 33, 40, 43, 44, 50, 54, 55, 60, 65, 76, 87])

In [162]:
np.sort(array_3D, axis = None)


array([ 1,  2,  3,  4,  5,  5, 11, 11, 12, 13, 14, 15, 21, 31, 41, 51, 51, 52, 53, 54])

In [163]:
# ### 6. For the 3 arrays:
#     A) Find the mean.
#     B) Find the median.
#     C) Find the mean along the columns.

In [164]:
np.mean(array_1D)


22.5

In [165]:
np.mean(array_2D)


46.0

In [166]:
np.mean(array_3D)

22.5

In [167]:
np.median(array_1D)

12.0

In [168]:
np.mean(array_2D,axis=1)

array([40., 65., 33.])

In [169]:
# ### 7. For the 2D array:
#     A) Find the variance. 
#     B) Find the standard deviation. 
#     C) Find the covariance. 
#     D) Find the correlation. 

In [170]:
np.var(array_2D)

416.6666666666667

In [171]:
np.std(array_2D)

20.412414523193153

In [172]:
np.cov(array_2D)

array([[250. , 275. , 275. ],
       [275. , 302.5, 302.5],
       [275. , 302.5, 302.5]])

In [173]:
np.corrcoef(array_2D)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [174]:
# ### 10. Run the following cell, and then compute the following:
#     A) The mean, using the np.mean() function.
#     B) The mean, using the np.nanmean() function.
#     C) The variance, using the np.var() function. 
#     D) The variance, using the np.nanvar() funcion. 

In [175]:
array_nan = np.array([[20,np.nan,40,50,60], [np.nan,54,65,np.nan,87], [11,22,33,44,np.nan]])
array_nan

array([[20., nan, 40., 50., 60.],
       [nan, 54., 65., nan, 87.],
       [11., 22., 33., 44., nan]])

In [176]:
np.nanmean(array_nan)

44.18181818181818

In [177]:
np.mean(array_nan)

nan

In [178]:
np.var(array_nan)

nan

In [179]:
np.nanvar(array_nan)

451.6033057851239