In [366]:
import numpy as np

In [367]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [368]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [369]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [370]:
### 2. Slice the first column of the 2-D array. 

In [374]:
array_2D[:,0]

array([20, 43, 11])

In [375]:
### 3. Slice the last column of the 2-D array

In [377]:
array_2D[:,-1]

array([60, 87, 55])

In [378]:
### 4. Slice the second row of the 2-D array

In [379]:
array_2D[1,:]

array([43, 54, 65, 76, 87])

In [380]:
### 5. Slice the last two columns of the 2-nd row of the 2-D array

In [385]:
array_2D[1,3:5]

array([76, 87])

In [386]:
### 6. Slice the 2-nd row of the 2-D array excluding the last two columns

In [389]:
array_2D[1,0:3]

array([43, 54, 65])

In [390]:
### 7. Slice everything excluding the first row and last column of the 2-D array

In [395]:
array_2D[1:,0:-1]

array([[43, 54, 65, 76],
       [11, 22, 33, 44]])

In [396]:
### 8. Slice the 1st, 3rd and 5th columns of the 2-D array


In [403]:
array_2D[::,::2]

array([[20, 40, 60],
       [43, 65, 87],
       [11, 33, 55]])

In [404]:
### 9. Slice the first columns of both matrices in the 3-D array


In [405]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [407]:
array_3D[:,:,:1]

array([[[ 1],
        [11]],

       [[11],
        [51]]])

In [408]:
### 10. Slice every other column of both matrices in the 3-D array

In [416]:
array_3D[:,:,1:]

array([[[ 2,  3,  4,  5],
        [21, 31, 41, 51]],

       [[12, 13, 14, 15],
        [52, 53, 54,  5]]])

In [417]:
### 11. Use conditional slicing to check if the individual elements of each array satisfy a given condition (e.g. greater than 10)

In [420]:
array_2D[array_2D[:,:]>10]

array([20, 30, 40, 50, 60, 43, 54, 65, 76, 87, 11, 22, 33, 44, 55])

In [421]:
### 13. Add a second condition and disaply which individual elements satisfy both (e.g. greater than 10 and odd)

In [427]:
array_2D[(array_2D[:,:]>10 )| (array_2D[:,:]%2 != 0)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [430]:
# ### 14. Call the first row of the first 2-D array in the 3-D array in 3 different ways:
#     A) Use precise indices for both dimensions. 
#     B) Use a precise index for one dimension and a slice for the second dimension. 
#     C) Uses slices (from the origin, up to the second value) for both dimensions.a 

In [431]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [433]:
array_3D[0][0]

array([1, 2, 3, 4, 5])

In [444]:
array_3D[:1,:1]

array([[[1, 2, 3, 4, 5]]])

In [448]:
array_3D[:1,:1,:]

array([[[1, 2, 3, 4, 5]]])

In [449]:
array_3D[0][0].shape

(5,)

In [455]:
array_3D[:1,:1].squeeze().shape


(5,)

In [456]:
array_3D[:1,:1,:].squeeze().shape

(5,)