In [278]:
import numpy as np

In [279]:
# working with arrays

matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [280]:
# basic slicing

In [281]:
# slice: contains part or entire rows of an original array

In [286]:
# slice with start and end row both being 0
matrix_a[0:0]

array([], shape=(0, 3), dtype=int32)

In [291]:
# gives 1 st row of the matrix
matrix_a[1:3]

array([[4, 5, 6]])

In [292]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [293]:
type(matrix_a[:,:])

numpy.ndarray

In [296]:

matrix_a [1:]

array([[4, 5, 6]])

In [298]:
matrix_a[2:]

array([], shape=(0, 3), dtype=int32)

In [299]:
#  notations

# indexing is very similar to slicing 
# indexing = specific indexing
# slicing = interval indexing


In [300]:
matrix_a[0]

array([1, 2, 3])

In [301]:
matrix_a[:1]

array([[1, 2, 3]])

In [302]:
matrix_a[1:]

array([[4, 5, 6]])

In [304]:
matrix_a[1]

array([4, 5, 6])

In [306]:
matrix_a[:-1]

array([[1, 2, 3]])

In [308]:
matrix_a[-1:]

array([[4, 5, 6]])

In [311]:
# all rows and columns begining from the 1st column
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [312]:
# second row and columns
matrix_a[:1,1:]

array([[2, 3]])