In [328]:
import numpy as np

In [329]:
matrix_c = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,0,0]])

In [330]:
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 0, 0]])

In [331]:
# conditional slicing

In [332]:
matrix_c[:,0]

array([1, 3, 4])

In [333]:
matrix_c[:,0] > 2

array([False,  True,  True])

In [335]:
matrix_c[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [336]:
# gives value which satisfys the given condition
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3])

In [337]:
matrix_c[matrix_c[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3])

In [338]:
matrix_c[matrix_c[:,:] %2 == 0]

array([2, 0, 6, 6, 4, 4, 0, 0])

In [339]:
# multiple conditions simaltaneously

In [345]:
matrix_c[(matrix_c[:,:] %2 == 0 )| (matrix_c[:,:] <= 4)]

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 0, 0])