In [313]:
import numpy as np

In [325]:
# stepwise splicing

# slicing where we donot take consecutive values
# values which are a certain distance apart given by steps

In [315]:
matrix_b = np.array([[1,1,1,2,0],[3,6,5,4,7],[4,5,3,8,0]])

In [316]:
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 5, 4, 7],
       [4, 5, 3, 8, 0]])

In [318]:
matrix_b[::,::]

array([[1, 1, 1, 2, 0],
       [3, 6, 5, 4, 7],
       [4, 5, 3, 8, 0]])

In [319]:
# syntax:
#     matrix_b[start:end:step]

In [324]:
matrix_b[::1,::2]

array([[1, 1, 0],
       [3, 5, 7],
       [4, 3, 0]])

In [327]:
matrix_b[-1::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])