In [31]:
import numpy as np

In [34]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                           )
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [33]:
# partial cleaning while importing

In [35]:
# skips header removes from top of dataset

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        skip_header=2   )
lending_co_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [36]:
# remove from bottom as defined by skip_footer

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        skip_footer=2   )
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [37]:
# discard columns
# use only column 0

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        usecols=0  )
lending_co_data_numeric_NAN

array([2000., 2000., 1000., ...,   nan, 1000., 2000.])

In [38]:
#multiple columns

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        usecols=(1,2,3,4)  )
lending_co_data_numeric_NAN

array([[  40.,  365., 3121., 4241.],
       [  40.,  365., 3061., 4171.],
       [  40.,  365., 2160., 3280.],
       ...,
       [  40.,  365., 4201., 5001.],
       [  40.,  365., 2080., 3320.],
       [  40.,  365., 4601., 4601.]])

In [39]:

lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        usecols=(1,2,3,4) ,skip_footer=2, skip_header=2 )
lending_co_data_numeric_NAN

array([[  40.,  365., 2160., 3280.],
       [  40.,  365., 3041., 4241.],
       [  50.,  365., 3470., 4820.],
       ...,
       [  40.,  365., 3401.,   nan],
       [  40.,  365.,   nan, 5440.],
       [  40.,  365., 4201., 5001.]])

In [40]:
# splitting columns into variables


In [41]:

lending_co_data1,lending_co_data2,lending_co_data3, lending_data_4 = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                        usecols=(1,2,3,4) ,skip_footer=2, skip_header=2, unpack=True )
lending_co_data_numeric_NAN

array([[  40.,  365., 2160., 3280.],
       [  40.,  365., 3041., 4241.],
       [  50.,  365., 3470., 4820.],
       ...,
       [  40.,  365., 3401.,   nan],
       [  40.,  365.,   nan, 5440.],
       [  40.,  365., 4201., 5001.]])

In [42]:
print(lending_co_data1)
print(lending_co_data2)
print(lending_co_data3)
print(lending_data_4)

[40. 40. 50. ... 40. 40. 40.]
[365. 365. 365. ... 365. 365. 365.]
[2160. 3041. 3470. ... 3401.   nan 4201.]
[3280. 4241. 4820. ...   nan 5440. 5001.]
