In [1]:
import numpy as np

In [2]:
# np.loadtext() vs np.genfromtxt()

In [4]:
# loadtext-load values data ready to be used and imported
# genfromtxt- create dataset from text file , customize it

In [14]:
lending_co_data_numeric_1 = np.loadtxt(r"C:\Users\97798\Desktop\1.1 Lending-Company-Numeric-Data.csv", delimiter=',')


In [15]:
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [16]:
lending_co_data_numeric_2 = np.genfromtxt(r"C:\Users\97798\Desktop\1.1 Lending-Company-Numeric-Data.csv", delimiter=',')


In [17]:
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [20]:
# check if two arrays are equal to one another

np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [21]:
# data with missing entries

In [23]:
lending_co_data_numeric_NAN = np.loadtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';')


ValueError: could not convert string '' to float64 at row 11, column 4.

In [24]:
# solving this issue

In [25]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';')


In [26]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [27]:
# genfrom text works well with nan data points

In [30]:
lending_co_data_numeric_NAN = np.genfromtxt(r"C:\Users\97798\Desktop\1.3 Lending-Company-Numeric-Data-NAN.csv", delimiter=';',
                                           dtype = np.str_)
lending_co_data_numeric_NAN


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')