# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.version

<module 'numpy.version' from 'C:\\Users\\97798\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
a=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
a.itemsize * a.size

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
a= np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10,51
         )

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
a = np.array([1,2,3,4,5,6,7,8,9])
a = np.flip(a)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [33]:
a = np.array([1,2,0,0,4,0])
a
np.argwhere(a[:] == 0)

array([[2],
       [3],
       [5]], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [36]:
np.random.randn(27).reshape(3,3,3)

array([[[-0.30635915,  1.41236416, -0.62169083],
        [ 0.68921832,  0.8281943 ,  0.45587008],
        [-0.45906587, -1.21528361, -0.29536581]],

       [[-0.0095564 ,  2.67140938,  0.44852229],
        [-0.63301046, -1.32293462,  1.40479557],
        [-1.08799357,  1.63430782, -0.06544566]],

       [[ 0.19537954,  0.31898516, -0.22486615],
        [ 1.74820314, -1.2902965 , -0.88341601],
        [-0.4776658 , -0.28663632, -1.49480821]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
a=np.random.randn(100).reshape(10,10)
a

np.max(a)
np.min(a)

-2.3185087719910014

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
np.mean(np.random.random(30))

0.47638530543317115

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
# Define the dimensions of the array
n_rows = 5
n_cols = 5

# Create a new array with zeros
arr = np.zeros((n_rows, n_cols), dtype=int)

# Set the first and last rows to 1
arr[0, :] = 1
arr[-1, :] = 1

# Set the first and last columns to 1, except for the corners which are already 1
arr[1:-1, 0] = 1
arr[1:-1, -1] = 1

# Print the resulting array
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
# Define the dimensions of the array
n_rows = 5
n_cols = 5

# Create a new array with zeros
arr = np.zeros((n_rows, n_cols), dtype=int)

# Set the first and last rows to 1
arr[0, :] = 0
arr[-1, :] = 0

# Set the first and last columns to 1, except for the corners which are already 1
arr[1:-1, 0] = 0
arr[1:-1, -1] = 0

# Print the resulting array
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [9]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [13]:
np.zeros((5,5))

matrix = np.tril(np.array([1,2,3,4]))
matrix

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
matrix = np.zeros((8,8))
matrix

matrix[::2,::2]=1
matrix[1::2,1::2]=1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
matrix = np.zeros([6,7,8])
matrix

np.unravel_index(100,matrix.shape)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
matrix = np.zeros((8,8))
matrix

black_square = np.array([[0, 1], [1, 0]])
white_square = np.array([[1, 0], [0, 1]])

# Use tile to create an 8x8 chessboard pattern
chessboard = np.tile(np.bmat([[black_square, white_square], [white_square, black_square]]), (4, 4))[:8, :8]

print(chessboard)

[[0 1 1 0 0 1 1 0]
 [1 0 0 1 1 0 0 1]
 [1 0 0 1 1 0 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 1 0 0 1 1 0]
 [1 0 0 1 1 0 0 1]
 [1 0 0 1 1 0 0 1]
 [0 1 1 0 0 1 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [28]:
matrix = np.random.random((5,5))
matrix

norm_matrix = np.linalg.norm(matrix, axis=1, keepdims=True)
norm_matrix[norm_matrix == 0] = 1
matrix_normalized = matrix / norm_matrix
matrix_normalized

array([[0.57909758, 0.30110697, 0.48117059, 0.43060122, 0.39628025],
       [0.03276498, 0.16371904, 0.70590865, 0.42259182, 0.54335224],
       [0.0688854 , 0.64080073, 0.16884825, 0.40585168, 0.62562282],
       [0.48903001, 0.59518189, 0.4512475 , 0.32022655, 0.31692083],
       [0.31939034, 0.38143534, 0.05247854, 0.52320427, 0.68992767]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [29]:

# Define custom dtype for RGBA color
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

# Create a 1D array of colors using the custom dtype
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
matrix_1 = np.random.random((5,3))
matrix_1

matrix_2 = np.random.random((3,2))
matrix_2

matrix_1.dot(matrix_2)

array([[0.21232956, 0.87231736],
       [0.28962283, 1.04422089],
       [0.14576833, 0.584348  ],
       [0.2278553 , 0.66254255],
       [0.14477777, 0.5314691 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
a= np.array([1,2,3,4,5,6,7,8,9])

a[(a>=3) & (a<=8) ]*= -1
a

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9])

 #### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
np.array(0)/np.array(0)

np.array(0)//np.array(0)

np.array([np.nan]).astype(int).astype(float)

C:\Users\97798\AppData\Local\Temp\ipykernel_14012\3335945171.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)
C:\Users\97798\AppData\Local\Temp\ipykernel_14012\3335945171.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)
C:\Users\97798\AppData\Local\Temp\ipykernel_14012\3335945171.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
a = np.array([1.2,3,4,5.6,7.8])
np.ceil(a)
print(np.ceil(a))

[2. 3. 4. 6. 8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [60]:
array_1 = np.array([1,2,3,4,5,6,7,8,9])
array_2=np.arange(5,10)
array_1
array_2
np.intersect1d(array_1,array_2)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [61]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\97798\AppData\Local\Temp\ipykernel_14012\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
from datetime import datetime, timedelta

today = datetime.today()
today
print("Today is {}".format(today))

yesterday = datetime.today()  - timedelta()
yesterday
print("Yesterday is {}".format(yesterday))

tomorrow = datetime.today() + timedelta()
tomorrow
print("Tomorrow is {}".format(tomorrow))

Today is 2023-05-10 11:12:17.065084
Yesterday is 2023-05-10 11:12:17.065084
Tomorrow is 2023-05-10 11:12:17.066084


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [75]:
dates = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')

july_months = dates[np.datetime_as_string(dates, unit = 'M') == '2016-07']

print(july_months)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [82]:
A = np.array([1, 2, 3], dtype = np.float32)
B = np.array([4, 5, 6],dtype = np.float32)

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)
np.multiply(A, np.negative(A/2), out=A)
print(A)

[-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [87]:
a = np.array([1.2,2.3,3.4,4.5,5.6,7.8,9.0])

np.trunc(a)

np.ceil(a)

np.floor(a)

np.round(a)

array([1., 2., 3., 4., 6., 8., 9.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [91]:
row_vector = np.arange(5)

matrix = row_vector.reshape(-1, 1) + np.zeros((5, 5))

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [102]:
def generate_integers():
    for i in range(10):
        yield i

array = np.fromiter(generate_integers(),dtype =int) 
print(array)
        

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [105]:
vector = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [110]:
vector = np.random.randn(10)
vector
np.sort(vector)

array([-0.68161817, -0.61827161, -0.26867211, -0.01740531,  0.02739586,
        0.1959559 ,  0.85110368,  1.18772364,  1.4365472 ,  1.51292277])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [120]:
import time

a= np.random.rand(100)
a

start_time = time.time()
sum1 = np.sum(a)
end_time = time.time()
time_taken = end_time - start_time
print(time_taken)
print(sum)

start_time = time.time()
sum_2 = sum(a)
end_time = time.time()
time_taken = end_time - start_time
print(time_taken)
print(sum1)

0.0
52.65045859665538


TypeError: 'numpy.float64' object is not callable

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [121]:
matrix_A = np.arange(1,100)
matrix_b = np.arange(50,100)
np.array_equal(matrix_A,matrix_b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [124]:
matrix_A.flags.writeable == False 

matrix_A[5] = 100
matrix_A

array([  1,   2,   3,   4,   5, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [125]:
cartesian = np.random.rand(10, 2)


magnitude = np.linalg.norm(cartesian, axis=1)
angle = np.arctan2(cartesian[:, 1], cartesian[:, 0])


polar = np.column_stack((magnitude, angle))

print("Cartesian coordinates:")
print(cartesian)
print("Polar coordinates:")
print(polar)

Cartesian coordinates:
[[0.27292408 0.47962231]
 [0.88547944 0.72231058]
 [0.92909701 0.27117017]
 [0.39651108 0.59355341]
 [0.80237722 0.90742071]
 [0.6059114  0.92894439]
 [0.93930279 0.77352538]
 [0.85867863 0.88959885]
 [0.70436195 0.64507321]
 [0.61792748 0.25013408]]
Polar coordinates:
[[0.55183794 1.053453  ]
 [1.14271887 0.68425802]
 [0.9678608  0.28397616]
 [0.71381138 0.98185094]
 [1.21128921 0.84675725]
 [1.10908355 0.99283541]
 [1.21681192 0.68891291]
 [1.23641219 0.80308243]
 [0.95511529 0.74149044]
 [0.6666344  0.38463333]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [131]:
a= np.random.randn(10)

max_val = np.max(a)
max_val

a[a==max_val] = 0
a

array([ 0.30331758, -0.09996253,  0.16761974, -0.81388337, -0.18304811,
       -0.92191386,  0.        ,  1.29258479,  0.15140888, -0.74269328])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [132]:


# Define the data type for the structured array
dtype = [('x', float), ('y', float)]

# Define the number of points in each dimension
n = 5

# Create a grid of x and y values using NumPy's meshgrid function
x, y = np.meshgrid(np.linspace(0, 1, n), np.linspace(0, 1, n))

# Combine the x and y arrays into a single structured array
points = np.empty((n**2,), dtype=dtype)
points['x'] = x.ravel()
points['y'] = y.ravel()

# Print the resulting structured array
print(points)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [133]:
n =5
indices = np.arange(n)

cauchy_matrix = 1.0 / (indices[:, np.newaxis] - indices[np.newaxis, :])
print(cauchy_matrix)

[[        inf -1.         -0.5        -0.33333333 -0.25      ]
 [ 1.                 inf -1.         -0.5        -0.33333333]
 [ 0.5         1.                 inf -1.         -0.5       ]
 [ 0.33333333  0.5         1.                 inf -1.        ]
 [ 0.25        0.33333333  0.5         1.                 inf]]


C:\Users\97798\AppData\Local\Temp\ipykernel_14012\2187076719.py:4: RuntimeWarning: divide by zero encountered in divide
  cauchy_matrix = 1.0 / (indices[:, np.newaxis] - indices[np.newaxis, :])


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [136]:


# List of all NumPy scalar types
dtypes = [np.bool_, np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64, np.float16, np.float32, np.float64, np.complex64, np.complex128]

# Loop over all scalar types and print the min and max value
for dtype in dtypes:
    info = np.finfo(dtype) if np.issubdtype(dtype, np.integer) else np.finfo(dtype)
    print(f"{dtype.__name__:8}   min: {info.min:<20}   max: {info.max:<20}")


ValueError: data type <class 'numpy.bool_'> not inexact

#### 49. How to print all the values of an array? (★★☆)

In [137]:
array_1 = np.array([1,2,3,4,5,6,7,8,9,0])
print(array_1[:])

[1 2 3 4 5 6 7 8 9 0]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [140]:
vec = np.random.randn(10)
vec

np.absolute(vec)

array([1.04310134, 2.37986438, 1.00066441, 0.25104118, 1.76567873,
       0.62062994, 1.00281059, 0.59972838, 1.65664237, 0.770836  ])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [141]:


# Define the data type for the structured array
dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', float), ('g', float), ('b', float)])]

# Create a structured array with two elements
arr = np.zeros(2, dtype=dtype)

# Set values for the first element
arr[0]['position']['x'] = 1.0
arr[0]['position']['y'] = 2.0
arr[0]['color']['r'] = 0.5
arr[0]['color']['g'] = 0.2
arr[0]['color']['b'] = 0.8

# Set values for the second element
arr[1]['position']['x'] = 3.0
arr[1]['position']['y'] = 4.0
arr[1]['color']['r'] = 0.1
arr[1]['color']['g'] = 0.9
arr[1]['color']['b'] = 0.3

# Print the structured array
print(arr)


[((1., 2.), (0.5, 0.2, 0.8)) ((3., 4.), (0.1, 0.9, 0.3))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [144]:
random_vector = np.random.random((100,2))
from scipy.spatial.distance import cdist

distances = cdist(random_vector, random_vector)
print(distances)

C:\Users\97798\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


[[0.         0.67738622 0.74621978 ... 0.34286943 0.22179041 0.33771638]
 [0.67738622 0.         0.28012282 ... 1.01914675 0.88053435 0.34086599]
 [0.74621978 0.28012282 0.         ... 1.06187522 0.96731663 0.46446945]
 ...
 [0.34286943 1.01914675 1.06187522 ... 0.         0.19738072 0.68045605]
 [0.22179041 0.88053435 0.96731663 ... 0.19738072 0.         0.54054571]
 [0.33771638 0.34086599 0.46446945 ... 0.68045605 0.54054571 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [146]:
a = np.arange(100,dtype = np.float32).astype(dtype=np.int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [147]:

# Create a 5x5 array with zeros
arr = np.zeros((5,5))

# Define the probability of placing an element
p = 0.2

# Compute the number of elements to be placed
num_elements = int(p * arr.size)

# Generate random indices for the elements to be placed
indices = np.random.choice(arr.size, num_elements, replace=False)

# Assign the desired value (e.g. 1) to the selected indices
arr.flat[indices] = 1

print(arr)


[[1. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [157]:
matrix = np.arange(12).reshape(4,3)
matrix

means = np.mean(matrix, axis= 0)
means

difference = matrix - means
print(difference)

[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [158]:


# Create a 3x3 array
arr = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

# Sort the array by the second column
n = 1  # 0-indexed
indices = np.argsort(arr[:, n])
arr_sorted = arr[indices]

print(arr_sorted)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [159]:

# Create a 3x3 array
arr = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

# Sort the array by the second column
n = 1  # 0-indexed
indices = np.argsort(arr[:, n])
arr_sorted = arr[indices]

print(arr_sorted)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [160]:
np.abs(matrix)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [173]:
matrix = np.arange(3).reshape(1,3)
matrix_1 = np.arange(3).reshape(3,1)

matrix_iter = np.nditer(matrix)
matrix_1_iter = np.nditer(matrix_1)
matrix_1_iter

In [174]:
matrix
matrix_1
sum = 0

# Loop over the elements of the arrays and sum them up
for i in range(3):
    for j in range(3):
        if i == j:
            sum += next(matrix_iter) + next(matrix_1_iter)

print(sum)

6


#### 63. Create an array class that has a name attribute (★★☆)

In [175]:

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [177]:

# Given vector
v = np.array([1, 2, 3, 4, 5])

# Index vector
idx = np.array([0, 2, 4, 0, 3])

# Add 1 to elements indexed by the second vector
np.add.at(v, idx, 1)

print(v)


[3 2 4 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [178]:
import numpy as np

# Input vector X and index list I
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 0, 1, 1, 2, 2, 2])

# Create an array F with the same shape as the unique values of I
F = np.zeros(np.unique(I).shape)

# Accumulate the values of X to F based on the values of I
np.add.at(F, I, X)

print(F) # Output: [ 3.  7. 12.]


ValueError: array is not broadcastable to correct shape

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [179]:

# Create a random image
w, h = 100, 100
img = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array of shape (w*h, 3)
img_2d = img.reshape((w*h, 3))

# Find the unique colors
unique_colors = np.unique(img_2d, axis=0)

# Print the number of unique colors
print("Number of unique colors:", unique_colors.shape[0])


Number of unique colors: 9999


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [182]:
arr = np.random.rand(2, 3, 4, 5)

sum =np.sum(arr,axis= (2,3))
print(sum)

[[10.70243219 11.06409002 10.78518082]
 [ 9.14557167 11.008289   10.0433257 ]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [184]:

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3])

means = np.bincount(S, weights=D) / np.bincount(S)

print(means)


[1.5 4.  7.  9.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [186]:
# create two matrices
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)

# compute dot product and extract diagonal
C = np.einsum('ij,jk->ik', A, B)
diagonal = np.diagonal(C)
print(diagonal)

[0.75135673 1.09630953 1.21023263]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [190]:

v = np.array([1, 2, 3, 4, 5])
n_zeros = 3
z = np.zeros(n_zeros, dtype=int)
result = np.insert(v, np.arange(len(v)) * (n_zeros+1), z)
print(result)

IndexError: index 10 is out of bounds for axis 0 with size 10

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [204]:
a = np.random.random((5,5,3))
b = np.random.random((5,5))
b = b[:,:,np.newaxis]

result = a * b
print(result)

[[[0.01959851 0.02166554 0.01757627]
  [0.22718956 0.6751252  0.0367754 ]
  [0.06600985 0.04802249 0.005159  ]
  [0.20167432 0.06535318 0.3090754 ]
  [0.24980004 0.05817179 0.09784854]]

 [[0.20338066 0.00156335 0.34050877]
  [0.01976634 0.00565833 0.22035796]
  [0.14531801 0.16127814 0.30155422]
  [0.21128397 0.33270702 0.03807821]
  [0.00989597 0.07268389 0.03495619]]

 [[0.17986012 0.01077516 0.11689429]
  [0.63100891 0.16145335 0.60867668]
  [0.05615862 0.18173862 0.11094866]
  [0.25121421 0.19129284 0.17247244]
  [0.55011081 0.53396875 0.11615571]]

 [[0.72130189 0.03414262 0.70575537]
  [0.24437051 0.56095913 0.19622075]
  [0.55394773 0.20915134 0.15404222]
  [0.12170354 0.01130228 0.52988104]
  [0.2537861  0.03887584 0.17943314]]

 [[0.19922966 0.48808954 0.03532865]
  [0.49922794 0.2007965  0.7582568 ]
  [0.01333495 0.0236231  0.0359812 ]
  [0.00540638 0.03067838 0.01258787]
  [0.40285413 0.66248878 0.58444716]]]


#### 72. How to swap two rows of an array? (★★★)

In [206]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr[0] = arr[2]
print(arr)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [207]:


# create a set of 10 triplets describing 10 triangles
triangles = np.random.randint(0, 10, size=(10, 3))

# extract all the line segments from the triangles
segments = set()
for triangle in triangles:
    a, b, c = triangle
    segment1 = (min(a, b), max(a, b))
    segment2 = (min(b, c), max(b, c))
    segment3 = (min(c, a), max(c, a))
    segments.update([segment1, segment2, segment3])

# print the set of unique line segments
print(segments)


{(4, 9), (1, 6), (1, 3), (2, 8), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (8, 8), (2, 4), (0, 4), (1, 5), (1, 8), (7, 9), (4, 7), (3, 5), (4, 4), (0, 9), (1, 4), (2, 6), (6, 6), (7, 8)}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [208]:

# create a sorted array C that corresponds to a bincount
C = np.array([0, 1, 2, 2, 3, 3, 3, 4])

# produce an array A such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

# print the resulting array A
print(A)


[1 2 2 3 3 4 4 4 5 5 5 6 6 6 7 7 7 7]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [211]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr
 
k = 3
kernels = np.ones(k)/k

averages = np.convolve(arr,kernels,mode='valid')
print(averages)

[2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [212]:

# Define the one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6])

# Define the window size and number of rows in the output array
win_size = 3
num_rows = len(Z) - win_size + 1

# Create the two-dimensional array using stride_tricks.as_strided()
strides = Z.strides + (Z.strides[0],)
Z_2d = np.lib.stride_tricks.as_strided(Z, shape=(num_rows, win_size), strides=strides)

# Print the two-dimensional array
print(Z_2d)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [214]:
a = True
b = not a

print(a) # True
print(b) # False

True
False


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [222]:
def distance_to_lines(P0, P1, p):
    # Compute the direction vectors of the lines
    u = P1 - P0
    
    # Compute the vector from P0 to p
    v = p - P0
    
    # Compute the cross product of u and v
    cross_product = np.cross(u, v)
    
    # Compute the magnitude of u
    u_mag = np.linalg.norm(u, axis=1)
    
    # Compute the distance to each line
    distance = np.abs(cross_product) / u_mag
    
    return distance

# Define the lines and the point
P0 = np.array([[1, 1], [2, 3], [4, 5]])
P1 = np.array([[4, 4], [6, 7], [8, 9]])
p = np.array([3, 2])

# Compute the distance from p to each line
distance = distance_to_lines(P0, P1, p)

# Print the distances
print(distance)


[0.70710678 1.41421356 1.41421356]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [223]:

def extract_subpart(arr, shape, center, fill_value=0):
    # Compute the indices of the subpart
    indices = [slice(c - s // 2, c + (s + 1) // 2) for c, s in zip(center, shape)]
    
    # Create a new array of the desired shape, filled with the fill value
    subpart = np.full(shape, fill_value, dtype=arr.dtype)
    
    # Compute the overlap between the subpart and the array
    overlap = [slice(max(0, -i.start), min(s, s - i.stop)) for i, s in zip(indices, arr.shape)]
    
    # Copy the overlapping region from the array into the subpart
    subpart[overlap] = arr[indices][overlap]
    
    return subpart


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [229]:
Z= np.array( [1,2,3,4,5,6,7,8,9,10,11,12,13,14])
Z

window_size = 4

# Generate the sliding window view of the array
Z_view = np.lib.stride_tricks.sliding_window_view(Z, window_size)

# Extract the rows from the sliding window view
R = [row for row in Z_view]

# Convert the list to a numpy array
R = np.array(R)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [232]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A

np.linalg.matrix_rank(A)

2

#### 83. How to find the most frequent value in an array?

In [233]:
unique_vals, counts = np.unique(A, return_counts=True)

# Find the index of the maximum count
max_count_idx = np.argmax(counts)

# Get the most frequent value
most_frequent_val = unique_vals[max_count_idx]

print("Most frequent value:", most_frequent_val)

Most frequent value: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [237]:
matrix = np.random.randn(10,10)
matrix

blocks = []
for i in range(8):  # iterate over the rows
    for j in range(8):  # iterate over the columns
        block = matrix[i:i+3, j:j+3]  # extract the 3x3 submatrix
        blocks.append(block)

# Print the blocks
for block in blocks:
    print(block)
    

[[ 1.26866707  1.11155711 -1.3808223 ]
 [ 1.57123028 -0.68151428  0.25841341]
 [ 0.94549452 -2.42778381  0.35552575]]
[[ 1.11155711 -1.3808223  -0.73986624]
 [-0.68151428  0.25841341 -0.2068629 ]
 [-2.42778381  0.35552575 -1.40690989]]
[[-1.3808223  -0.73986624 -0.66957848]
 [ 0.25841341 -0.2068629  -0.22149683]
 [ 0.35552575 -1.40690989 -0.63561692]]
[[-0.73986624 -0.66957848 -0.05502118]
 [-0.2068629  -0.22149683  0.55761168]
 [-1.40690989 -0.63561692  0.72738586]]
[[-0.66957848 -0.05502118  1.1987568 ]
 [-0.22149683  0.55761168 -0.13236373]
 [-0.63561692  0.72738586  0.06616587]]
[[-0.05502118  1.1987568  -0.36380133]
 [ 0.55761168 -0.13236373 -0.07141921]
 [ 0.72738586  0.06616587 -0.39361902]]
[[ 1.1987568  -0.36380133  0.90812861]
 [-0.13236373 -0.07141921  0.29605885]
 [ 0.06616587 -0.39361902 -0.06570087]]
[[-0.36380133  0.90812861 -1.83583016]
 [-0.07141921  0.29605885 -2.14536349]
 [-0.39361902 -0.06570087  1.0792499 ]]
[[ 1.57123028 -0.68151428  0.25841341]
 [ 0.94549452 -2.

 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [238]:

class SymmetricArray(np.ndarray):
    def __getitem__(self, index):
        i, j = index
        if i <= j:
            return super().__getitem__((i, j))
        else:
            return super().__getitem__((j, i))
    
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [245]:

# create a 16x16 array
arr = np.random.randint(10, size=(16, 16))

# reshape the array into a 4x4 grid of 4x4 blocks
blocks = arr.reshape(4, 4, 4, 4)

# sum the blocks along the last two dimensions
block_sum = np.sum(blocks, axis=(-2, -1))

print(block_sum)


[[53 94 67 67]
 [78 85 75 83]
 [65 87 71 67]
 [82 84 73 81]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [249]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
n = 3
largest_value = arr[np.argpartition(-arr,n)[:n]]
print(largest_value)

[9 6 5]


In [247]:
arr

array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [251]:
import itertools

# Define some example vectors
v1 = [1, 2, 3]
v2 = ['a', 'b']
v3 = [True, False]

# Compute the cartesian product of the vectors
cartesian_product = list(itertools.product(v1, v2, v3))

print(cartesian_product)


[(1, 'a', True), (1, 'a', False), (1, 'b', True), (1, 'b', False), (2, 'a', True), (2, 'a', False), (2, 'b', True), (2, 'b', False), (3, 'a', True), (3, 'a', False), (3, 'b', True), (3, 'b', False)]


#### 91. How to create a record array from a regular array? (★★★)

In [252]:

# Create a regular array
data = np.array([[1, 2], [3, 4], [5, 6]])

# Create a record array from the regular array
names = ['field1', 'field2']  # Field names for the record array
dtype = [(name, data.dtype) for name in names]  # Data types for the record array fields
record_array = np.rec.fromarrays(data.transpose(), dtype=dtype)

print(record_array)


[(1, 2) (3, 4) (5, 6)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [256]:
z = np.arange(1,1000)
z
z = z^3
z

array([  2,   1,   0,   7,   6,   5,   4,  11,  10,   9,   8,  15,  14,
        13,  12,  19,  18,  17,  16,  23,  22,  21,  20,  27,  26,  25,
        24,  31,  30,  29,  28,  35,  34,  33,  32,  39,  38,  37,  36,
        43,  42,  41,  40,  47,  46,  45,  44,  51,  50,  49,  48,  55,
        54,  53,  52,  59,  58,  57,  56,  63,  62,  61,  60,  67,  66,
        65,  64,  71,  70,  69,  68,  75,  74,  73,  72,  79,  78,  77,
        76,  83,  82,  81,  80,  87,  86,  85,  84,  91,  90,  89,  88,
        95,  94,  93,  92,  99,  98,  97,  96, 103, 102, 101, 100, 107,
       106, 105, 104, 111, 110, 109, 108, 115, 114, 113, 112, 119, 118,
       117, 116, 123, 122, 121, 120, 127, 126, 125, 124, 131, 130, 129,
       128, 135, 134, 133, 132, 139, 138, 137, 136, 143, 142, 141, 140,
       147, 146, 145, 144, 151, 150, 149, 148, 155, 154, 153, 152, 159,
       158, 157, 156, 163, 162, 161, 160, 167, 166, 165, 164, 171, 170,
       169, 168, 175, 174, 173, 172, 179, 178, 177, 176, 183, 18

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [257]:

# Define arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6], [2, 3, 1], [7, 8, 9], [2, 5, 1], [1, 3, 2], [8, 9, 7], [5, 6, 4]])
B = np.array([[1, 2], [2, 3]])

# Check for rows of A that contain elements of each row of B regardless of order
mask = np.logical_and.reduce(np.isin(A[:, :, None], B.T), axis=1).any(axis=1)
result = A[mask]

print(result)


[[1 2 3]
 [2 3 1]
 [1 3 2]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [258]:

# Define a 10x3 matrix
matrix = np.array([[1, 2, 3], [4, 4, 4], [5, 6, 6], [7, 7, 8], [9, 10, 11], [12, 12, 12], [13, 14, 14], [15, 16, 16], [17, 17, 17], [18, 19, 20]])

# Extract rows with unequal values
num_unique = np.apply_along_axis(lambda x: len(np.unique(x)), axis=1, arr=matrix)
result = matrix[num_unique > 1]

print(result)


[[ 1  2  3]
 [ 5  6  6]
 [ 7  7  8]
 [ 9 10 11]
 [13 14 14]
 [15 16 16]
 [18 19 20]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [259]:

# Define a vector of integers
vec = np.array([2, 5, 7])

# Convert the vector to a matrix binary representation
bin_mat = np.unpackbits(vec[:, np.newaxis].astype(np.uint8), axis=1)

print(bin_mat)


[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [261]:
matrix

unique_rows = np.unique(matrix,axis = 0)
print(unique_rows)

[[ 1  2  3]
 [ 4  4  4]
 [ 5  6  6]
 [ 7  7  8]
 [ 9 10 11]
 [12 12 12]
 [13 14 14]
 [15 16 16]
 [17 17 17]
 [18 19 20]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)