In [1]:
import numpy as np

In [3]:
# Write a NumPy program to find the dot product of two arrays of different dimensions.

nums1 = np.array([[1, 2], [3, 4], [5, 6]])
nums2 = np.array([7, 8])
print("Original arrays:")
print(nums1)
print(nums2)

Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]


In [4]:
np.dot(nums1,nums2)

array([23, 53, 83])

In [5]:
# Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.

matrix = np.identity(3)

In [6]:
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
vertical_stack = np.vstack((matrix,matrix,matrix))

In [9]:
vertical_stack

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
horizontal_stack = np.hstack((matrix,matrix,matrix))

In [11]:
horizontal_stack

array([[1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [14]:
# Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

a= np.random.random((4,4))

In [15]:
a

array([[0.40977881, 0.63926678, 0.14306947, 0.25944309],
       [0.61157059, 0.83865199, 0.96644586, 0.64005603],
       [0.26071056, 0.49694576, 0.02176555, 0.84440688],
       [0.86908582, 0.2235753 , 0.15250635, 0.63865154]])

In [16]:
np.sum(a,axis =1)

array([1.45155815, 3.05672446, 1.62382876, 1.88381901])

In [18]:
# Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element. 

arr = np.random.random((3,3))

In [19]:
mean_values = np.mean(arr,axis=1)

In [20]:
print(mean_values)

[0.51206631 0.87551536 0.48854857]


In [21]:
arr = arr - mean_values

In [22]:
print(arr)

[[ 0.12819138 -0.61375922  0.14563654]
 [ 0.46106365 -0.21616046  0.50551265]
 [ 0.43931271 -0.58893695 -0.26086028]]


In [23]:
# Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element. 

In [24]:
arr

array([[ 0.12819138, -0.61375922,  0.14563654],
       [ 0.46106365, -0.21616046,  0.50551265],
       [ 0.43931271, -0.58893695, -0.26086028]])

In [25]:
mean_column_wise = np.mean(arr, axis = 0)
print(mean_column_wise)

[ 0.34285591 -0.47295221  0.1300963 ]


In [26]:
arr = arr -mean_column_wise

In [27]:
print(arr)

[[-0.21466453 -0.14080701  0.01554024]
 [ 0.11820774  0.25679175  0.37541635]
 [ 0.0964568  -0.11598474 -0.39095658]]


In [28]:
# Write a NumPy program to create a 5x5 array with random values and normalize it row-wise. 

arr = np.random.random((5,5))

In [29]:
arr

array([[0.22971707, 0.84564472, 0.73763404, 0.97629796, 0.27824341],
       [0.97555658, 0.94719969, 0.62099798, 0.37343373, 0.01310488],
       [0.79933597, 0.68032897, 0.27188104, 0.26780657, 0.95205442],
       [0.01313288, 0.70480407, 0.45594994, 0.8569024 , 0.09521359],
       [0.11526443, 0.18541077, 0.84706474, 0.53455723, 0.75153595]])

In [32]:
norm_arr = arr / np.linalg.norm(arr, axis=1, keepdims=True)
print("\nNormalize Array row-wise:")
print(norm_arr)


Normalize Array row-wise:
[[0.15008847 0.55251239 0.48194228 0.6378763  0.18179376]
 [0.63313656 0.61473293 0.40302791 0.24235862 0.00850507]
 [0.54465734 0.46356749 0.18525628 0.18247998 0.64871775]
 [0.01091319 0.58567986 0.37888643 0.71207091 0.07912083]
 [0.09067961 0.14586439 0.66639379 0.4205412  0.59124039]]


In [33]:
#  Write a NumPy program to create a 5x5 array with random values and normalize it column-wise. 

norm_arr = arr / np.linalg.norm(arr, axis=0, keepdims=True)
print("\nNormalize Array Column-wise:")
print(norm_arr)


Normalize Array Column-wise:
[[0.17846298 0.5238148  0.53108846 0.66057157 0.22292521]
 [0.75789203 0.58672065 0.44711177 0.25266846 0.01049947]
 [0.62098946 0.42141383 0.19575138 0.18120022 0.76277434]
 [0.01020269 0.43657436 0.32827898 0.57978751 0.07628397]
 [0.08954682 0.11484835 0.60987737 0.36168601 0.6021214 ]]


In [34]:
# Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

arr =np.random.random((3,3,3))

In [35]:
arr

array([[[7.75098549e-01, 6.97320673e-01, 5.83516807e-01],
        [5.74884662e-01, 1.20505034e-01, 2.52466378e-01],
        [9.87929294e-01, 3.29500199e-01, 7.56309953e-01]],

       [[2.85684046e-01, 4.74567915e-01, 3.20255741e-01],
        [7.50857471e-01, 6.95865383e-01, 8.87058418e-01],
        [5.28401620e-01, 5.83922286e-01, 8.12518726e-01]],

       [[9.17314291e-01, 4.60015780e-01, 1.68378642e-01],
        [6.46699277e-01, 3.65505259e-01, 7.36933667e-04],
        [1.93354636e-01, 1.97427835e-01, 9.45627204e-02]]])

In [36]:
np.sum(arr, axis = -1)

array([[2.05593603, 0.94785607, 2.07373945],
       [1.0805077 , 2.33378127, 1.92484263],
       [1.54570871, 1.01294147, 0.48534519]])

In [37]:
#  Write a NumPy program to create a 5x5 array with random values and sort each row. 

In [40]:
arr = np.random.random((5,5))

In [41]:
arr

array([[0.34527759, 0.68983896, 0.88426754, 0.88871205, 0.68492123],
       [0.77086168, 0.29016077, 0.00389681, 0.27775836, 0.55091277],
       [0.17000818, 0.25106571, 0.28459236, 0.20759113, 0.92964076],
       [0.428823  , 0.81206892, 0.6664439 , 0.95040024, 0.18926872],
       [0.39425256, 0.74654767, 0.71272004, 0.75004476, 0.32495236]])

In [42]:
np.sort(arr,axis=1)

array([[0.34527759, 0.68492123, 0.68983896, 0.88426754, 0.88871205],
       [0.00389681, 0.27775836, 0.29016077, 0.55091277, 0.77086168],
       [0.17000818, 0.20759113, 0.25106571, 0.28459236, 0.92964076],
       [0.18926872, 0.428823  , 0.6664439 , 0.81206892, 0.95040024],
       [0.32495236, 0.39425256, 0.71272004, 0.74654767, 0.75004476]])

In [43]:
# Write a NumPy program to create a 5x5 array with random values and sort each column. 

np.sort(arr, axis =0)

array([[0.17000818, 0.25106571, 0.00389681, 0.20759113, 0.18926872],
       [0.34527759, 0.29016077, 0.28459236, 0.27775836, 0.32495236],
       [0.39425256, 0.68983896, 0.6664439 , 0.75004476, 0.55091277],
       [0.428823  , 0.74654767, 0.71272004, 0.88871205, 0.68492123],
       [0.77086168, 0.81206892, 0.88426754, 0.95040024, 0.92964076]])

In [44]:
#Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row. 

In [46]:
nums = np.random.random((5,5))

In [47]:
print(nums)

[[0.25588293 0.63671775 0.62791762 0.86283018 0.53144367]
 [0.54875082 0.39837557 0.33537626 0.46944235 0.67407752]
 [0.65809366 0.98728001 0.70456306 0.41720402 0.9802833 ]
 [0.58431316 0.93186778 0.27901528 0.37422857 0.52006935]
 [0.8682785  0.51025684 0.13203306 0.67614657 0.83513512]]


In [48]:
second_largest = np.partition(nums,-2,axis =1 )[:,-2]
print(second_largest)

[0.63671775 0.54875082 0.9802833  0.58431316 0.83513512]


In [49]:
# Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column. 

second_largest = np.partition(nums,-2,axis =0 )[:,-2]
print(second_largest)

[0.37422857 0.41720402 0.46944235 0.67614657 0.86283018]


In [59]:
# Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0. 
matrix = np.random.random((5,5))

In [60]:
print(matrix)

[[0.31172218 0.54833128 0.6335731  0.95536951 0.0342931 ]
 [0.26492479 0.93042374 0.69478201 0.75552011 0.00480323]
 [0.65217318 0.77613216 0.46161795 0.20899384 0.7250774 ]
 [0.16820698 0.91967361 0.41033693 0.57256092 0.01086904]
 [0.83919882 0.58369317 0.86512889 0.52963212 0.65093536]]


In [62]:
max_value = np.max(matrix)
print(max_value)

0.9553695109125371


In [64]:
nums[nums == max_value] = 0

nums

In [65]:
nums

array([[0.25588293, 0.63671775, 0.62791762, 0.86283018, 0.53144367],
       [0.54875082, 0.39837557, 0.33537626, 0.46944235, 0.67407752],
       [0.65809366, 0.98728001, 0.70456306, 0.41720402, 0.9802833 ],
       [0.58431316, 0.93186778, 0.27901528, 0.37422857, 0.52006935],
       [0.8682785 , 0.51025684, 0.13203306, 0.67614657, 0.83513512]])

In [66]:
# Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0. 

min_values = np.min(matrix)
print(min_values)

0.004803230202853004


In [68]:
nums[nums == min_values] = 0

In [69]:
print(nums)

[[0.25588293 0.63671775 0.62791762 0.86283018 0.53144367]
 [0.54875082 0.39837557 0.33537626 0.46944235 0.67407752]
 [0.65809366 0.98728001 0.70456306 0.41720402 0.9802833 ]
 [0.58431316 0.93186778 0.27901528 0.37422857 0.52006935]
 [0.8682785  0.51025684 0.13203306 0.67614657 0.83513512]]


In [70]:
#  Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element

matrix

array([[0.31172218, 0.54833128, 0.6335731 , 0.95536951, 0.0342931 ],
       [0.26492479, 0.93042374, 0.69478201, 0.75552011, 0.00480323],
       [0.65217318, 0.77613216, 0.46161795, 0.20899384, 0.7250774 ],
       [0.16820698, 0.91967361, 0.41033693, 0.57256092, 0.01086904],
       [0.83919882, 0.58369317, 0.86512889, 0.52963212, 0.65093536]])

In [71]:
np.exp(matrix)

array([[1.36577519, 1.73036312, 1.88433146, 2.599631  , 1.03488789],
       [1.30333295, 2.53558337, 2.00327234, 2.1287184 , 1.00481478],
       [1.91970817, 2.17305098, 1.58663901, 1.2324374 , 2.06489092],
       [1.18318148, 2.50847151, 1.50732557, 1.77280124, 1.01092832],
       [2.31451189, 1.79264676, 2.37531221, 1.69830743, 1.91733339]])