In [1]:
import numpy as np

In [4]:
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])

In [5]:
p

array([[1, 0],
       [0, 1]])

In [6]:
q


array([[1, 2],
       [3, 4]])

In [7]:
#  Write a NumPy program to compute the multiplication of two given matrixes

In [9]:
np.dot(p,q)

array([[1, 2],
       [3, 4]])

In [11]:
# Write a NumPy program to compute the outer product of two given vectors.
np.outer(p,q)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

In [12]:
#  Write a NumPy program to compute the cross product of two given vectors.

np.cross(p,q)

array([ 2, -3])

In [13]:
# Write a NumPy program to compute the determinant of a given square array
a = np.array([[1, 0], [1, 2]])
np.linalg.det(a)

2.0

In [14]:
# Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays


a = np.array([1,2,3])
b = np.array([0,1,0])

In [21]:
result = np.einsum("n,n",a,b)
print(result)

2


In [19]:
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

In [22]:
result = np.einsum("mk,kn", x, y)
print(result)

[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [23]:
# Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.a

In [24]:
import numpy as np
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
print 
result = np.inner(a, b)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)


Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [25]:
# Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

a = np.array([1,2,5])
b = np.array([2,1,0])

In [27]:
import numpy as np
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)


Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [28]:
# Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays

a = np.array([1,2,3])
b = np.array([0,1,0])

In [29]:
np.kron(a,b)

array([0, 1, 0, 0, 2, 0, 0, 3, 0])

In [34]:
x = np.arange(9).reshape(3,3)
y = np.arange(15).reshape(5,3)

In [35]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
np.kron(x,y)

array([[  0,   0,   0,   0,   1,   2,   0,   2,   4],
       [  0,   0,   0,   3,   4,   5,   6,   8,  10],
       [  0,   0,   0,   6,   7,   8,  12,  14,  16],
       [  0,   0,   0,   9,  10,  11,  18,  20,  22],
       [  0,   0,   0,  12,  13,  14,  24,  26,  28],
       [  0,   3,   6,   0,   4,   8,   0,   5,  10],
       [  9,  12,  15,  12,  16,  20,  15,  20,  25],
       [ 18,  21,  24,  24,  28,  32,  30,  35,  40],
       [ 27,  30,  33,  36,  40,  44,  45,  50,  55],
       [ 36,  39,  42,  48,  52,  56,  60,  65,  70],
       [  0,   6,  12,   0,   7,  14,   0,   8,  16],
       [ 18,  24,  30,  21,  28,  35,  24,  32,  40],
       [ 36,  42,  48,  42,  49,  56,  48,  56,  64],
       [ 54,  60,  66,  63,  70,  77,  72,  80,  88],
       [ 72,  78,  84,  84,  91,  98,  96, 104, 112]])

In [38]:
# Write a NumPy program to compute the condition number of a given matrix.

a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])

np.linalg.cond(a)

1.4142135623730951

In [39]:
# Write a NumPy program to find a matrix or vector norm.
v = np.arange(7)
np.linalg.norm(v)

9.539392014169456

In [40]:
# Write a NumPy program to compute the determinant of an array. 
a = np.array([[1,2],[3,4]])

np.linalg.det(a)

-2.0000000000000004

In [41]:
# Write a NumPy program to compute the inverse of a given matrix.

m = np.array([[1,2],[3,4]])
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
#  Write a NumPy program to calculate the QR decomposition of a given matrix.

m = np.array([[1,2],[3,4]])
np.linalg.qr(m)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

In [43]:
# Write a NumPy program to compute the sum of the diagonal element of a given array
m = np.arange(6).reshape(2,3)


In [44]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
np.trace(m)

4

In [46]:
# Write a NumPy program to get the lower-triangular L in the Cholesky decomposition of a given array

a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)

np.linalg.cholesky(a)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8., -5.,  3.]])

In [47]:
# Write a NumPy program to get the qr factorization of a given array. 

a = np.array([[4, 12, -14], [12, 37, -53], [-14, -53, 98]], dtype=np.int32)
np.linalg.qr(a)

(array([[-0.21199958, -0.27930103,  0.93650794],
        [-0.63599873, -0.68815735, -0.34920635],
        [ 0.74199852, -0.66964945, -0.03174603]]),
 array([[-18.86796226, -65.4018692 , 109.39178122],
        [  0.        ,   6.67798664, -25.24309237],
        [  0.        ,   0.        ,   2.28571429]]))

In [48]:
# Write a NumPy program to compute the factor of a given array by Singular Value Decomposition

a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)

np.linalg.svd(a,full_matrices=False)


(array([[ 0.,  1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0., -1.,  0.]], dtype=float32),
 array([3.      , 2.236068, 2.      , 0.      ], dtype=float32),
 array([[-0.       ,  0.       ,  1.       , -0.       ,  0.       ],
        [ 0.4472136,  0.       ,  0.       ,  0.       ,  0.8944272],
        [ 0.       , -1.       ,  0.       ,  0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ,  0.       ]],
       dtype=float32))

In [49]:
# Write a NumPy program to calculate the Frobenius norm and the condition number of a given array.

In [50]:
a = np.arange(1, 10).reshape((3, 3))


In [51]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.linalg.norm(a,'fro')

16.881943016134134

In [54]:
np.linalg.cond(a,'fro')

inf