In [166]:
import numpy as np

In [167]:
original_array = np.array([[10,40],[30,20]])
original_array

array([[10, 40],
       [30, 20]])

In [170]:
np.sort(original_array,axis=0)

array([[10, 20],
       [30, 40]])

In [171]:
np.sort(original_array,axis=1)

array([[10, 40],
       [20, 30]])

In [173]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height

data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type) 

In [174]:
np.sort(students,order='height')

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [175]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equa
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type) 



In [176]:
students

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [177]:
np.sort(students,order=['class','height'])

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [178]:
# Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

In [179]:
indices = np.lexsort((student_id, student_height))


In [180]:
indices

array([4, 0, 5, 3, 6, 1, 2], dtype=int64)

In [181]:
for n in indices:
    print(student_id[n],student_height[n])

1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [182]:
# Write a NumPy program to get the indices of the sorted elements of a given array.

original_array = np.array([1023,5202,6230,1671,1682,5241,4532])
original_array

array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [183]:
np.argsort(original_array)

array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [184]:
# Write a NumPy program to sort a given complex array using the real part first, then the imaginary part

original_array = np.array([(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)])
original_array

array([1.+2.j, 3.-1.j, 3.-2.j, 4.-3.j, 3.+5.j])

In [186]:
np.sort_complex(original_array)

array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

In [187]:
# Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print(nums)

[ 70  50  20  30 -11  60  50  40]


In [188]:
np.partition(nums,4)

array([-11,  30,  20,  40,  50,  50,  60,  70])

In [189]:
#  Write a NumPy program to sort the specified number of elements from beginning of a given array.

nums =  np.random.rand(10)
print(nums)

[0.01824712 0.10220809 0.93221962 0.11209784 0.29603326 0.32436191
 0.19576896 0.27590223 0.21122384 0.4063564 ]


In [191]:
nums[np.argpartition(nums,range(5))]

array([0.01824712, 0.10220809, 0.11209784, 0.19576896, 0.21122384,
       0.32436191, 0.93221962, 0.27590223, 0.29603326, 0.4063564 ])

In [192]:
# Write a NumPy program to sort an given array by the nth column.

original_array = np.array([[1,5,0],[3,2,5],[8,7,6]])
original_array

array([[1, 5, 0],
       [3, 2, 5],
       [8, 7, 6]])

In [197]:
original_array[original_array[:,1].argsort()]

array([[3, 2, 5],
       [1, 5, 0],
       [8, 7, 6]])