In [252]:
import numpy as np

In [253]:
#  Write a NumPy program to generate five random numbers from the normal distribution

np.random.randn(5)

array([ 0.4144573 ,  0.47983894, -2.80509677,  2.17583599, -1.06214571])

In [257]:
# Write a NumPy program to generate six random integers between 10 and 30

np.random.randint(10,30,6)

array([15, 29, 12, 20, 17, 23])

In [259]:
# Write a NumPy program to create a 3x3x3 array with random values.

np.random.random((3,3,3))

array([[[0.01804713, 0.25703254, 0.09863202],
        [0.79467605, 0.28621635, 0.46447325],
        [0.26068634, 0.79743163, 0.2890685 ]],

       [[0.52580026, 0.09108775, 0.5668311 ],
        [0.42618305, 0.58182059, 0.07702791],
        [0.70138904, 0.11075771, 0.27509678]],

       [[0.02258236, 0.53384547, 0.78664736],
        [0.41506682, 0.65558073, 0.25184496],
        [0.02013036, 0.47752871, 0.2894493 ]]])

In [262]:
# Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values

a=np.random.random((5,5))

In [263]:
a

array([[0.7874849 , 0.87122318, 0.43137081, 0.18076772, 0.31447327],
       [0.79071394, 0.18535622, 0.53009451, 0.89693479, 0.79683595],
       [0.68506286, 0.01056198, 0.25975899, 0.04614256, 0.48162204],
       [0.55351936, 0.52617481, 0.8941411 , 0.90217019, 0.45508559],
       [0.57383822, 0.6630308 , 0.89180902, 0.60064282, 0.90844465]])

In [264]:
np.max(a)

0.9084446460323524

In [265]:
np.min(a)

0.010561980775894764

In [269]:
# Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

np.random.random((10,4))[0:5]

array([[4.99018207e-01, 2.40260307e-01, 7.54289393e-01, 3.94146683e-01],
       [8.53867680e-01, 8.56861131e-01, 3.77208141e-01, 8.31299810e-01],
       [4.70683696e-01, 2.67273287e-01, 5.86903477e-01, 5.69870068e-01],
       [7.98397654e-01, 7.77952416e-02, 5.06586232e-01, 4.43938165e-01],
       [4.80596449e-01, 9.82278941e-02, 7.90710155e-01, 5.51251084e-04]])

In [270]:
# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

a = np.arange(10)

In [271]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
np.random.shuffle(a)

In [274]:
a

array([4, 0, 2, 8, 7, 6, 5, 3, 9, 1])

In [275]:
np.random.permutation(10)

array([4, 3, 7, 5, 6, 9, 1, 8, 0, 2])

In [276]:
# Write a NumPy program to normalize a 3x3 random matrix.

x= np.random.random((3,3))
print("Original Array:")
print(x)

Original Array:
[[0.98089468 0.69449883 0.30140124]
 [0.73485521 0.38361232 0.57546227]
 [0.48752151 0.04892225 0.91213157]]


In [280]:
row_norms = np.linalg.norm(x, axis=1)

# divide each row by its norm
normalized_mat = x / row_norms[:, np.newaxis]

# print the result
print(normalized_mat)

[[0.79162977 0.56049438 0.24324548]
 [0.72821238 0.38014461 0.5702603 ]
 [0.47085299 0.04724959 0.88094548]]


In [289]:
# Write a NumPy program to create a random vector of size 10 and sort it

a= np.random.random(10)

In [290]:
a

array([0.29167987, 0.24608517, 0.31906777, 0.58422213, 0.93373854,
       0.09815076, 0.70858158, 0.80558721, 0.82487517, 0.84543522])

In [291]:
a.sort()

In [292]:
a

array([0.09815076, 0.24608517, 0.29167987, 0.31906777, 0.58422213,
       0.70858158, 0.80558721, 0.82487517, 0.84543522, 0.93373854])

In [293]:
# Write a NumPy program to find the nearest value from a given value in an arraya
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)


3.8247359526098386


In [294]:
#  Write a NumPy program to check two random arrays are equal or not.

first_array = np.array([1,0,1,0,1,1])
second_array = np.array([0,0,1,1,1,0])

In [295]:
np.array_equal(first_array,second_array)

False

In [296]:
#  Write a NumPy program to create random vector of size 15 and replace the maximum value by -1

a = np.random.random(15)

In [297]:
np.max(a)

0.7463653357833565

In [298]:
a

array([0.39694489, 0.24708503, 0.66186043, 0.61557929, 0.42945863,
       0.49936903, 0.38080614, 0.21269631, 0.50326879, 0.61924088,
       0.63492935, 0.28378629, 0.39192175, 0.1674391 , 0.74636534])

In [301]:
a[a.argmax()] = -1

In [302]:
a

array([ 0.39694489,  0.24708503,  0.66186043,  0.61557929,  0.42945863,
        0.49936903,  0.38080614,  0.21269631,  0.50326879,  0.61924088,
        0.63492935,  0.28378629,  0.39192175,  0.1674391 , -1.        ])

In [303]:
# Write a NumPy program to find point by point distances of a random vector with shape (10,2) representing coordinates.

a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.74917635 0.48201277 0.39889617 0.56215555 0.19655291
  0.34379575 0.43824656 0.4397541  0.41646233]
 [0.74917635 0.         0.7986195  0.90114212 0.54458129 0.75792212
  0.83298984 0.31750923 0.82842505 0.34503375]
 [0.48201277 0.7986195  0.         0.18201959 0.29059775 0.67213424
  0.82220981 0.61648096 0.06718509 0.61987067]
 [0.39889617 0.90114212 0.18201959 0.         0.44894105 0.59514954
  0.73963692 0.66571581 0.11521459 0.66058118]
 [0.56215555 0.54458129 0.29059775 0.44894105 0.         0.70778328
  0.84943808 0.45880872 0.34327483 0.47566903]
 [0.19655291 0.75792212 0.67213424 0.59514954 0.70778328 0.
  0.15021844 0.4434721  0.63384573 0.41415246]
 [0.34379575 0.83298984 0.82220981 0.73963692 0.84943808 0.15021844
  0.         0.5337444  0.78299333 0.50286266]
 [0.43824656 0.31750923 0.61648096 0.66571581 0.45880872 0.4434721
  0.5337444  0.         0.62342595 0.03095751]
 [0.4397541  0.82842505 0.06718509 0.11521459 0.34327483 0.63384573
  0.78299333 0.623425

In [304]:
# Write a NumPy program to find the most frequent value in an array

x = np.random.randint(0, 10, 40)


In [305]:
x

array([9, 3, 4, 4, 3, 6, 4, 4, 3, 9, 0, 0, 2, 3, 9, 5, 7, 5, 7, 3, 6, 2,
       7, 2, 2, 1, 9, 3, 8, 9, 1, 0, 4, 3, 4, 8, 2, 2, 8, 6])

In [306]:
np.argmax(np.bincount(x))

3

In [307]:
# Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates

np.random.random((10,2))


array([[0.37598181, 0.60063468],
       [0.48186759, 0.49508047],
       [0.80116334, 0.78273573],
       [0.01190281, 0.93960064],
       [0.46532723, 0.31360055],
       [0.22869269, 0.084596  ],
       [0.4888345 , 0.10147248],
       [0.4260593 , 0.8382115 ],
       [0.18305571, 0.85474394],
       [0.38137752, 0.11797016]])

In [308]:
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

In [309]:
print(r)

[ 40.49691346 139.62807741]


In [310]:
print(t)

[1.21780594 0.9072406 ]


In [311]:
# Write a NumPy program to find the closest value (to a given scalar) in an array.

x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
90.86147620538213
91


In [312]:
# Write a NumPy program to get the n largest values of an array.

original_array =np.array([0,1,2,3,4,5,6,7,8,9])
original_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [316]:
np.random.shuffle(original_array)
n=1

print (original_array[np.argsort(original_array)[-n:]])


[9]


In [318]:
# Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255)

np.random.randint(0,256,(300,400,5))

array([[[ 11,  66,  70,  90, 176],
        [187, 249, 188, 103, 137],
        [208, 239, 150, 240, 193],
        ...,
        [125, 252, 135, 125, 141],
        [230, 143, 185,  27, 242],
        [ 18,   2,  29, 181,  42]],

       [[149,  66,  39, 241,  42],
        [105,  45, 108, 208,  75],
        [210,  92, 248,  86,  48],
        ...,
        [ 22, 145,  19, 128, 224],
        [ 83, 245, 133,  71, 211],
        [163,  97,  99,  15,  18]],

       [[253, 179,  65,  50,  50],
        [184, 178,  63, 215,  14],
        [ 80, 232,  30, 151, 201],
        ...,
        [156, 244, 192, 199, 132],
        [186,  44, 206, 192,  47],
        [105,  39, 124, 225, 146]],

       ...,

       [[215, 177, 236, 251,  41],
        [ 66, 205,   3, 239, 185],
        [206, 121,  43,  18, 199],
        ...,
        [ 26,  62, 155,   9, 154],
        [186, 113, 213, 244, 251],
        [185,  17, 223,  85,   8]],

       [[186, 174, 252, 186, 237],
        [187, 149, 108, 187,  21],
        [197, 152