In [336]:
import numpy as np

In [341]:
# Write a NumPy program to concatenate element-wise two arrays of string

array_1 = np.array(['Python' 'PHP'])

In [342]:
array_1

array(['PythonPHP'], dtype='<U9')

In [343]:
array_2 = np.array([' Java' ' C++'])

In [344]:
array_2

array([' Java C++'], dtype='<U9')

In [350]:
np.char.add(array_1,array_2)

array(['PythonPHP Java C++'], dtype='<U18')

In [351]:
# Write a NumPy program to repeat all the elements three times of a given array of string

original_array = np.array(['Python', 'PHP' ,'Java' ,'C++']
)

In [352]:
original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [354]:
np.char.multiply(original_array,3
                )

array(['PythonPythonPython', 'PHPPHPPHP', 'JavaJavaJava', 'C++C++C++'],
      dtype='<U18')

In [355]:
# Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [356]:
np.char.upper(original_array)

array(['PYTHON', 'PHP', 'JAVA', 'C++'], dtype='<U6')

In [357]:
np.char.lower(original_array)

array(['python', 'php', 'java', 'c++'], dtype='<U6')

In [358]:
np.char.capitalize(original_array)

array(['Python', 'Php', 'Java', 'C++'], dtype='<U6')

In [359]:
np.char.swapcase(original_array)

array(['pYTHON', 'php', 'jAVA', 'c++'], dtype='<U6')

In [360]:
np.char.title(original_array)

array(['Python', 'Php', 'Java', 'C++'], dtype='<U6')

In [362]:
# Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.

x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str_)
x

array(['python exercises', 'PHP', 'java', 'C++'], dtype='<U16')

In [363]:
centered = np.char.center(x,15,fillchar='_')

In [364]:
left = np.char.ljust(x, 15,fillchar='_')
right = np.char.rjust(x,15,fillchar='_')


In [365]:
centered

array(['python exercise', '______PHP______', '______java_____',
       '______C++______'], dtype='<U15')

In [366]:
left

array(['python exercise', 'PHP____________', 'java___________',
       'C++____________'], dtype='<U15')

In [367]:
right

array(['python exercise', '____________PHP', '___________java',
       '____________C++'], dtype='<U15')

In [368]:
# Write a NumPy program to insert a space between characters of all the elements of a given array. 

original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [369]:
np.char.join(" ",original_array)

array(['P y t h o n', 'P H P', 'J a v a', 'C + +'], dtype='<U11')

In [373]:
# Write a NumPy program to encode all the elements of a given array in cp500 and decode it again

a=np.char.encode(original_array,'cp500')
a

array([b'\xd7\xa8\xa3\x88\x96\x95', b'\xd7\xc8\xd7', b'\xd1\x81\xa5\x81',
       b'\xc3NN'], dtype='|S6')

In [374]:
b=np.char.decode(a,'cp500')
b


array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [377]:
# Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array

x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str_)
print("Original Array:")



Original Array:


In [378]:
np.char.strip(x)

array(['python exercises', 'PHP', 'java', 'C++'], dtype='<U18')

In [379]:
#  Write a NumPy program to remove the leading whitespaces of all the elements of a given arra

In [380]:
original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [381]:
np.char.lstrip(original_array)

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [382]:
# Write a NumPy program to remove the trailing whitespaces of all the elements of a given array

np.char.rstrip(original_array)

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [383]:
# Write a NumPy program to split the element of a given array to multiple lines.


In [385]:
x = np.array(['Python\Exercises, Practice, Solution'], dtype=np.str_)
x


array(['Python\\Exercises, Practice, Solution'], dtype='<U36')

In [386]:
np.char.splitlines(x)

array([list(['Python\\Exercises, Practice, Solution'])], dtype=object)

In [388]:
# Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left.

x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str_)
print("\nOriginal Array:")


Original Array:


In [389]:
x

array(['2', '11', '234', '1234', '12345'], dtype='<U5')

In [390]:
np.char.zfill(x,5)

array(['00002', '00011', '00234', '01234', '12345'], dtype='<U5')

In [391]:
# Write a NumPy program to replace "PHP" with "Python" in the element of a given array.

original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [393]:
np.char.replace(original_array,'PHP','Python')

array(['Python', 'Python', 'Java', 'C++'], dtype='<U6')

In [394]:
# Write a NumPy program to test equal, not equal, greater equal, greater and less test of all the elements of two given arrays

x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str_)
x2 = np.array(['Hello', 'php', 'Java', 'examples', 'html'], dtype=np.str_)

In [395]:
np.char.equal(x1,x2)

array([ True, False, False,  True,  True])

In [396]:
np.char.less_equal(x1,x2)

array([ True,  True,  True,  True,  True])

In [397]:
np.char.greater_equal(x1,x2)

array([ True, False, False,  True,  True])

In [398]:
# Write a NumPy program to count the number of "P" in a given array, element-wise. 

original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [399]:
np.char.count(original_array,"P")

array([1, 2, 0, 0])

In [401]:
# Write a NumPy program to count the lowest index of "P" in a given array, element-wise.

x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str_)
print("\nOriginal Array:")
print(x1)
print("count the lowest index of ‘P’:")
r = np.char.find(x1, "P")
print(r)


Original Array:
['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
count the lowest index of ‘P’:
[ 0  0 -1  4 -1]


In [403]:
# Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only

x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str_)
print("\nOriginal Array:")
print(x)


Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']


In [404]:
np.char.isdigit(original_array)

array([False, False, False, False])

In [405]:
np.char.islower(original_array)

array([False, False, False, False])

In [406]:
np.char.isupper(original_array)

array([False,  True, False,  True])

In [407]:
# Write a NumPy program to check whether each element of a given array starts with "P".

original_array

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [408]:
np.char.startswith(original_array,'P')

array([ True,  True, False, False])

In [412]:
# Write a NumPy program to add two zeros to the beginning of each element of a given array of string values.

nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype=np.str_)
print("Original array:")
print(nums)

print(np.char.add(nums,'00'))

Original array:
['1.12' '2.23' '3.71' '4.23' '5.11']
['1.1200' '2.2300' '3.7100' '4.2300' '5.1100']


In [413]:
# Write a NumPy program to count a given word in each row of a given array of string values.

str1 = np.array([['Python','NumPy','Exercises'],
                 ['Python','Pandas','Exercises'],
                 ['Python','Machine learning','Python']])
print("Original array of string values:") 
print(str1)

Original array of string values:
[['Python' 'NumPy' 'Exercises']
 ['Python' 'Pandas' 'Exercises']
 ['Python' 'Machine learning' 'Python']]


In [414]:
np.char.count(str1,'Python')

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 1]])

In [415]:
# Write a NumPy program to split a given text into lines and split the single line into array values.

student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

In [417]:
print(student)

01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos


In [419]:
text_lines = student.splitlines()
text_lines = [r.split('\t') for r in text_lines]
result = np.array(text_lines, dtype=np.str_)

In [420]:
print(result)

[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]
