In [1]:
import numpy as np

In [2]:

# 1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

array = np.array([1,4])

In [3]:
array

array([1, 4])

In [5]:
np.sum(array)

5

In [8]:
np.subtract(1,4)

-3

In [9]:
np.multiply(1,4)

4

In [10]:
np.divide(1,4)

0.25

In [11]:
# Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2

np.logaddexp(1,2)

2.313261687518223

In [12]:
np.logaddexp2(1,2)

2.584962500721156

In [13]:
# 3. Write a NumPy program to get true division of the element-wise array inputs

original_array = np.array([0,1,2,3,4,5,6,7,8,9])

In [14]:
original_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.true_divide(original_array,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [18]:
# Write a NumPy program to get the largest integer smaller or equal to the division of the inputs

original_array = np.array([1,2,3,4])
original_array

array([1, 2, 3, 4])

In [19]:
np.true_divide(original_array,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [22]:
np.floor_divide(array,1.5)

array([0., 2.])

In [23]:
# Write a NumPy program to get the powers of an array values element-wise.

x= np.arange(7)
print(x)

[0 1 2 3 4 5 6]


In [24]:
print(np.power(x,3))

[  0   1   8  27  64 125 216]


In [25]:
#  Write a NumPy program to get the element-wise remainder of an array of division

x = np.arange(7)
print(x)

[0 1 2 3 4 5 6]


In [26]:
np.remainder(x,5)

array([0, 1, 2, 3, 4, 0, 1], dtype=int32)

In [29]:
#  Write a NumPy program to calculate the absolute value element-wise

original_array = np.array([-10.2,122.2,0.2])
original_array

array([-10.2, 122.2,   0.2])

In [32]:
np.absolute(original_array)

array([ 10.2, 122.2,   0.2])

In [34]:
# Write a NumPy program to round array elements to the given number of decimals

x = np.round([1.45, 1.50, 1.55])
x


array([1., 2., 2.])

In [36]:
x = np.round([0.3,0.5,0.6],decimals=1)
x

array([0.3, 0.5, 0.6])

In [38]:
x = np.round([0.2,2.0,2.0,4.0,4.0],decimals=0)
x


array([0., 2., 2., 4., 4.])

In [41]:
# Write a NumPy program to round elements of the array to the nearest integer.

original_array = np.array([-0.7 ,-1.5 ,-1.7, 0.3, 1.5 ,1.8, 2. ])
original_array

array([-0.7, -1.5, -1.7,  0.3,  1.5,  1.8,  2. ])

In [43]:
np.floor(original_array)

array([-1., -2., -2.,  0.,  1.,  1.,  2.])

In [44]:
# Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.

original_array = np.array([-1.6,-1.5,-0.3,0.1,1.4,1.8,2])

In [45]:
original_array

array([-1.6, -1.5, -0.3,  0.1,  1.4,  1.8,  2. ])

In [46]:
floor_array = np.floor(original_array)
floor_array

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [47]:
ceil_array = np.ceil(original_array)
ceil_array

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [48]:
truncated_array = np.trunc(original_array)
truncated_array

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [49]:
# Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix produc

x = np.random.random((5,3))
y = np.random.random((3,2))



In [50]:
x

array([[0.38353429, 0.60262652, 0.19834115],
       [0.08118196, 0.63047355, 0.67483046],
       [0.46325528, 0.50451382, 0.79130987],
       [0.20945312, 0.42699459, 0.46111103],
       [0.57516421, 0.02080071, 0.89933831]])

In [51]:
y

array([[0.76587393, 0.01396926],
       [0.66314986, 0.6065288 ],
       [0.78348417, 0.72539995]])

In [52]:
z=np.dot(x,y)
z

array([[0.84876776, 0.51474469],
       [1.00899258, 0.8730564 ],
       [1.30934217, 0.88648963],
       [0.80484928, 0.59640034],
       [1.15891459, 0.67303081]])

In [53]:
#  Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers

first_array = np.array([1+2j,3+4j])
second_array = np.array([5+6j,7+8j])


In [54]:
first_array

array([1.+2.j, 3.+4.j])

In [55]:
second_array

array([5.+6.j, 7.+8.j])

In [58]:
np.vdot(first_array,second_array)

(70-8j)

In [59]:
# rite a NumPy program to create an inner product of two arrays

x = np.arange(24).reshape((2,3,4))
y = np.arange(4)


In [60]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [62]:
y

array([0, 1, 2, 3])

In [63]:
z= np.inner(x,y)
z

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [64]:
# Write a NumPy program to generate inner, outer, and cross products of matrices and vectors

x = np.array([1,4,0])
y = np.array([2,2,1])


In [65]:
x

array([1, 4, 0])

In [66]:
y


array([2, 2, 1])

In [67]:
np.inner(x,y)

10

In [68]:
np.outer(x,y)

array([[2, 2, 1],
       [8, 8, 4],
       [0, 0, 0]])

In [69]:
np.cross(x,y)

array([ 4, -1, -6])

In [71]:
# Write a NumPy program to find the roots of the following polynomials. 

np.roots((1,-4,7))

array([2.+1.73205081j, 2.-1.73205081j])

In [73]:
np.roots((1,-11,9,11))

array([ 9.98873698,  1.67049354, -0.65923052])

In [74]:
# Write a NumPy program to compute the following polynomial values.

np.polyval([1,-4,7],2)

3

In [76]:
np.polyval([1,-11,9,11],3)

-34

In [77]:
# Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another

In [78]:
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)

In [79]:
x

(10, 20, 30)

In [80]:
y

(30, 40, 50)

In [81]:
P.polyadd(x,y)

array([40., 60., 80.])

In [82]:
P.polysub(x,y)

array([-20., -20., -20.])

In [83]:
P.polymul(x,y)

array([ 300., 1000., 2200., 2200., 1500.])

In [84]:
P.polydiv(x,y)

(array([0.6]), array([-8., -4.]))

In [85]:
# Write a NumPy program to calculate mean across dimension, in a 2D numpy array

original_array = np.array([[10,30],[20,60]])

In [86]:
original_array

array([[10, 30],
       [20, 60]])

In [88]:
np.mean(original_array,axis=0)

array([15., 45.])

In [89]:
np.mean(original_array,axis=1)

array([20., 40.])

In [92]:
# Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

a=np.random.randn(1000)

In [93]:
np.average(a)

-0.020276866473930476

In [94]:
np.std(a)

1.032218248734242

In [95]:
np.var(a)

1.0654745130199854

In [96]:
# Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a given array

x = np.array([-1., 0, 1.])


In [97]:
x

array([-1.,  0.,  1.])

In [98]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [99]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [100]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [101]:
# Write a NumPy program to convert angles from radians to degrees for all elements in a given array

input = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
input

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

In [102]:
np.rad2deg(input)

array([-180.,  -90.,   90.,  180.])

In [103]:
#  Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

input = np.array([-180., -90., 90., 180.])
input

array([-180.,  -90.,   90.,  180.])

In [104]:
np.deg2rad(input)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

In [105]:
# Write a NumPy program to calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent for all elements in a given array.

input = np.array([-1., 0, 1.])
input


array([-1.,  0.,  1.])

In [106]:
np.arcsinh(input)

array([-0.88137359,  0.        ,  0.88137359])

In [107]:
np.arccosh(input)


C:\Users\97798\AppData\Local\Temp\ipykernel_15388\2258910621.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(input)


array([nan, nan,  0.])

In [108]:
np.arctanh(input)

C:\Users\97798\AppData\Local\Temp\ipykernel_15388\2629460867.py:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(input)


array([-inf,   0.,  inf])

In [109]:
# Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array

original_array = np.array([[1,2,3],[4,5,6]])
original_array


array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.cumsum(original_array,axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [117]:
np.cumsum(original_array,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [118]:
np.cumsum(original_array)

array([ 1,  3,  6, 10, 15, 21])

In [119]:
# Write a NumPy program to calculate cumulative product of the elements along a given axis, sum over rows for each of the 3 columns and product over columns for each of the 2 rows of a given 3x3 array.

np.cumproduct(original_array)

array([  1,   2,   6,  24, 120, 720])

In [120]:
np.cumproduct(original_array,axis = 0)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

In [121]:
np.cumproduct(original_array,axis = 1)

array([[  1,   2,   6],
       [  4,  20, 120]])

In [122]:
# Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.

original_array = np.array([1,3,5,7,0])
original_array

array([1, 3, 5, 7, 0])

In [123]:
r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])
r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])
assert np.array_equiv(r1, r2)

In [124]:
print(r2)

[  0.   0.   1.   1. 200.]


In [125]:
# Write a NumPy program to compute ex, element-wise of a given array.

original_array = np.array([1,2,3,4])
original_array

array([1, 2, 3, 4])

In [126]:
np.exp(original_array)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [127]:
# Write a NumPy program to calculate exp(x) - 1 for all elements in a given

np.exp(original_array)-1

array([ 1.71828183,  6.3890561 , 19.08553692, 53.59815003])

In [130]:
#  Write a NumPy program to calculate 2p for all elements in a given array.

np.power(2,original_array)

array([ 2,  4,  8, 16], dtype=int32)

In [131]:
# Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array. 

original_array = np.array([1., 2.71828183, 7.3890561 ])
original_array

array([1.        , 2.71828183, 7.3890561 ])

In [132]:
np.log(original_array)

array([0., 1., 2.])

In [133]:
np.log10(original_array)

array([0.        , 0.43429448, 0.86858896])

In [134]:
np.log2(original_array)

array([0.        , 1.44269504, 2.88539008])

In [137]:
# Write a NumPy program to compute the natural logarithm of one plus each element of a given array in floating-point accuracy.

original_array = np.array([1.e-099, 1.e-100])
original_array

array([1.e-099, 1.e-100])

In [138]:
np.log1p(original_array)

array([1.e-099, 1.e-100])

In [140]:
# Write a NumPy program to check element-wise True/False of a given array where signbit is set.

sample_array = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
sample_array

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [142]:
np.signbit(sample_array)

array([ True,  True,  True,  True, False, False, False, False, False])

In [146]:
# Write a NumPy program to change the sign of a given array to that of a given array, element-wise

x1 = np.array([-1,0,1,2])
x1

array([-1,  0,  1,  2])

In [147]:
x2 = -2.1
x2

-2.1

In [148]:
np.copysign(x1,x2)

array([-1., -0., -1., -2.])

In [149]:
#  Write a NumPy program to compute numerical negative value for all elements in a given array.

original_array = np.array([0,1,-1])
original_array

array([ 0,  1, -1])

In [150]:
original_array * -1

array([ 0, -1,  1])

In [151]:
#  Write a NumPy program to compute the reciprocal for all elements in a given array.

original_array = np.array([1,2,0.2,0.3])
original_array

array([1. , 2. , 0.2, 0.3])

In [152]:
np.reciprocal(original_array)

array([1.        , 0.5       , 5.        , 3.33333333])

In [153]:
# Write a NumPy program to compute xy, element-wise where x, y are two given arrays.

array_1 = np.array([[1,2],[3,4]])
array_2 = np.array([[1,2],[2,1]])

In [154]:
array_1

array([[1, 2],
       [3, 4]])

In [155]:
array_2

array([[1, 2],
       [2, 1]])

In [156]:
array_1 * array_2

array([[1, 4],
       [6, 4]])

In [159]:
np.power(array_1,array_2)

array([[1, 4],
       [9, 4]])

In [161]:
# Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array

x = np.array([1,3,5,0,-1,-7,0,5])
x


array([ 1,  3,  5,  0, -1, -7,  0,  5])

In [162]:
r1 = np.sign(x)
r2 = np.copy(x)

In [163]:
r2[r2>0] = 1
r2[r2<0] = -1


In [164]:
assert np.array_equal(r1,r2)

In [165]:
print(r1)

[ 1  1  1  0 -1 -1  0  1]
