In [1]:
import numpy as np


In [220]:
#  Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

original_list = list([12.23,100,36.32])
type(original_list)

list

In [221]:
array = np.array(original_list)
array

array([ 12.23, 100.  ,  36.32])

In [222]:
type(array)

numpy.ndarray

In [223]:

# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [227]:
np.arange(2,11).reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [228]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11

array_zero = np.zeros(11
                     )

In [229]:
array_zero


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [230]:
array_zero[7] = 11

In [231]:
array_zero

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [236]:
# Write a NumPy program to create an array with values ranging from 12 to 38.

original = np.arange(12,39)
original

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [239]:
#  Write a NumPy program to reverse an array (the first element becomes the last).

reverse_array = original[::-1]
reverse_array

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [240]:
# Write a NumPy program to convert an array to a floating type. 

original_array = np.array([1,2,3,4])

In [243]:
original_array = original_array.astype(dtype = np.float32)
original_array

array([1., 2., 3., 4.], dtype=float32)

In [255]:
# Write a NumPy program to create a 2D array with 1 on the border and 0 inside

x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [256]:
x[1:-1,1:-1]=0


In [257]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [258]:
# Write a NumPy program to add a border (filled with 0's) around an existing array.
x = np.ones((5,5))
x


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [263]:
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)


In [264]:
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [269]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [270]:
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [271]:
#  Write a NumPy program to convert a list and tuple into arrays.

list_array = np.array(original_list)

In [272]:
list_array


array([ 12.23, 100.  ,  36.32])

In [275]:
my_tuple = ([8, 4, 6], [1, 2, 3])
            
tuple_array = np.asarray(my_tuple)
tuple_array            

array([[8, 4, 6],
       [1, 2, 3]])

In [280]:
#  Write a NumPy program to append values to the end of an array.
array = np.array([10,20,30])
added_value = list([40,50,60,70,80,90])
added_value

[40, 50, 60, 70, 80, 90]

In [282]:
array = np.append(array,added_value)

In [283]:
array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [286]:
# Write a NumPy program to create an empty and full array

x = np.empty((3,4))
x

array([[8.70783292e-312, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.18831764e-312, 6.82116729e-043, 5.28327738e-091,
        9.17103577e-072],
       [8.40643303e+164, 8.44628636e+169, 6.48224659e+170,
        4.93432906e+257]])

In [290]:
x = np.full((3,4),fill_value=6)

In [291]:
print(x)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [292]:
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array

fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)

In [296]:
c=(5*F/9 - 5*32/9).round(2)

In [297]:
c

array([-17.78, -11.11,   7.34,   1.11,  37.73,   0.  ])

In [298]:
# Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])

In [299]:
x.real
x.imag

array([0.])

In [300]:
y.real

array([0.70710678])

In [301]:
y.imag

array([0.70710678])

In [304]:
# Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.

print(x.size)

1


In [305]:
x.size * x.itemsize

16

In [306]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a second array
array_1 = np.array([0,10,20,40,60])
array_2 = np.array([0,40])

In [307]:
array_1

array([ 0, 10, 20, 40, 60])

In [308]:
array_2

array([ 0, 40])

In [310]:
np.intersect1d(array_1,array_2)

array([ 0, 40])

In [311]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [315]:
np.in1d(array_1,array_2)

array([ True, False, False,  True, False])

In [316]:
# Write a NumPy program to get the unique elements of an array

array=np.array([10,10,20,20,30,30])

In [317]:
array

array([10, 10, 20, 20, 30, 30])

In [318]:
np.unique(array)

array([10, 20, 30])

In [319]:
# Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in

array_1 = np.array([0,10,20,40,60,80])
array_2 = np.array([10,30,40,50,70,90])

In [320]:
np.setdiff1d(array_1,array_2)

array([ 0, 20, 60, 80])

In [321]:
# Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return sorted, distinct values in only one (not both) of the input arrays.4

np.setxor1d(array_1,array_2)

array([ 0, 20, 30, 50, 60, 70, 80, 90])

In [322]:
# Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays

np.union1d(array_1,array_2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [323]:
#  Write a NumPy program to test whether all elements in an array evaluate to True.

a[a[:] == True]

array([], dtype=float64)

In [327]:
# Write a NumPy program to construct an array by repeating
sample_array = np.array([1,2,3,4])
sample_array = np.tile(array,2)
sample_array

array([10, 10, 20, 20, 30, 30, 10, 10, 20, 20, 30, 30])

In [329]:
x = np.repeat(3, 4)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[1 1 2 2 3 3 4 4]


In [332]:
# Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array. 

original_array = np.array([1,2,3,4,5,6])
np.argmax(original_array)
np.argmin(original_array)

0

In [334]:
# Write a NumPy program to compare two arrays using NumPy.

array_a = [1,2]
array_b = [4,5]

In [337]:
np.greater_equal(array_a,array_b)

array([False, False])

In [338]:
np.greater(array_a,array_b)

array([False, False])

In [340]:
# Write a NumPy program to sort along the first and last axes of an array.

a = [[2,5],[4,4]]
np.sort(a,axis=0)

array([[2, 4],
       [4, 5]])

In [342]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

In [343]:
np.lexsort((first_names,last_names))

array([1, 3, 2, 4, 0], dtype=int64)

In [5]:
# Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array. 

original_array = np.array([[0,10,20],[20,30,40]])

indices = np.where(original_array[:]>10)

In [7]:
original_array[original_array > 10]

array([20, 20, 30, 40])

In [8]:
#  Write a NumPy program to save a NumPy array to a text file. 

np.savetxt("file",original_array)

In [12]:
#  Write a NumPy program to find the memory size of a NumPy array. 

memory_size = original_array.nbytes

In [15]:
print("The memory size is {} bytes".format(memory_size))

The memory size is 24 bytes


In [16]:
# Write a NumPy program to create an array of ones and zeros.

array = np.zeros(2,dtype = np.float32)

In [17]:
array

array([0., 0.], dtype=float32)

In [18]:
array = array.astype(dtype = np.int32)

In [19]:
array

array([0, 0])

In [20]:
#  Write a NumPy program to change an array's dimension. 

a= np.arange(6)

In [21]:
a.shape

(6,)

In [30]:
np.random.random((1,9))

array([[0.64627781, 0.99673958, 0.47246377, 0.1596238 , 0.84090129,
        0.29805551, 0.04097332, 0.99756442, 0.62287455]])

In [31]:
# Write a NumPy program to create a contiguous flattened array. a

original_array = np.array([[10,20,30],[20,40,50]])
original_array

array([[10, 20, 30],
       [20, 40, 50]])

In [33]:
original_array.flatten()

array([10, 20, 30, 20, 40, 50])

In [35]:
# Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array. 
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(type(x))	
print(x.shape)
print(x.dtype)


<class 'numpy.ndarray'>
(2, 3)
int32


In [36]:
# Write a NumPy program to create another shape from an array without changing its data. 
x.shape


(2, 3)

In [37]:
x.reshape(3,2)

array([[ 2,  4],
       [ 6,  6],
       [ 8, 10]])

In [38]:
# Write a NumPy program to change an array's data type.

original_array = np.array([[2,4,6],[6,8,10]]).astype(dtype = np.float64)

In [39]:
original_array

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

In [40]:
# Write a NumPy program to create a new array of 3*5, filled with 2. 

array = np.full((3,5),fill_value=2)

In [41]:
array

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [42]:
#   Write a NumPy program to create an array of 10's with the same shape and type as the given array
    
    x = np.arange(4, dtype=np.int64)

In [45]:
array = np.full_like(x,fill_value=10)

In [46]:
array

array([10, 10, 10, 10], dtype=int64)

In [47]:
# Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere. 

np.eye(3,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:

my_array = np.zeros((4, 4))

diagonal_values = np.array([1, 2, 3, 4])

np.fill_diagonal(my_array, diagonal_values)

print(my_array)


[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [59]:
#  Write a NumPy program to create a 1-D array with values from 0 to 50 and an array from 10 to 50.

np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [61]:
#  Write a NumPy program to create a 1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive. 

np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [62]:
# Write a NumPy program to create a 1-D array of 20 elements spaced evenly on a log scale between 2. and 5., exclusive

np.logspace(2,5,20)

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [63]:
# Write a NumPy program to create an array like the one below.

x= np.tri(4,3,-1)
x

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [69]:
# Write a NumPy program to create an array like the one below.

x = np.triu(np.arange(2,14).reshape(4,3),-1)

In [70]:
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

In [72]:
# Write a NumPy program to collapse a 3-D array into a one-dimensional array.

a = np.zeros((3,3))

In [73]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
a=np.eye(3,)

In [80]:
a.flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [87]:
# Write a NumPy program to find the 4th element of a specified array. 

original_array = np.array([[2,4,6],[6,8,10]])
flatten_array = original_array.flatten()

In [88]:
flatten_array[3]

6

In [89]:
print("Fourth element is {}".format(flatten_array[3]))

Fourth element is 6


In [92]:
# Write a NumPy program to change two array axes.

sample_array = np.array([[1,2,3]])
sample_array

array([[1, 2, 3]])

In [93]:
np.swapaxes(sample_array,0,1)

array([[1],
       [2],
       [3]])

In [94]:
# Write a NumPy program to move array axes to alternate positions. Other axes remain in their original order.

original_array = np.array([3,4,2])

In [95]:
original_array

array([3, 4, 2])

In [99]:
np.moveaxis(original_array,0,-1)

array([3, 4, 2])

In [100]:
np.moveaxis(original_array,-1,0)

array([3, 4, 2])

In [103]:
# Write a NumPy program to move the specified axis backwards, until it lies in a given position. 

original_array = np.array([2,3,4,5])
original_array

array([2, 3, 4, 5])

In [111]:

# Write a NumPy program to convert specified inputs into arrays with at least one dimension. 
x= 12.0
print(np.atleast_1d(x))
x = np.arange(6.0).reshape(2, 3)
print(np.atleast_1d(x))
print(np.atleast_1d(1, [3, 4]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
[array([1]), array([3, 4])]


In [112]:
# Write a NumPy program to insert a new axis within a 2-D array. 
x = np.zeros((3, 4))
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
y = np.expand_dims(x,axis=1)

In [114]:
y

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [115]:
y.shape

(3, 1, 4)

In [118]:
# Write a NumPy program to concatenate two 2-dimensional arrays. 

a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

c = np.concatenate((a,b),axis =1 )
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [120]:
# Write a NumPy program to convert 1-D arrays as columns into a 2-D array. 

sample_array = np.array([[10,20,30],[40,50,60]])
sample_array

array([[10, 20, 30],
       [40, 50, 60]])

In [123]:
sample_array.reshape((3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [124]:
# .Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.

original_array = np.arange(15
                          )

In [125]:
original_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [128]:
array_1 = original_array[0:2]

In [129]:
array_1

array([0, 1])

In [130]:
array_2 = original_array[2:6]

In [131]:
array_2

array([2, 3, 4, 5])

In [132]:
np.split(original_array,[2,6])

[array([0, 1]),
 array([2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])]

In [135]:
# Write a NumPy program that splits an array of shape 4x4 into two arrays along the second axis.
# Sample array :

x = np.arange(16).reshape(4,4)

In [136]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [137]:
np.hsplit(x,[2,6])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

In [138]:
# . Write a NumPy program to get the number of non-zero elements in an array.
# Expected Output:

original_array = np.array([[0,10,20],[20,30,40]])


In [139]:
original_array

array([[ 0, 10, 20],
       [20, 30, 40]])

In [140]:
original_array[:] >=0 

array([[ True,  True,  True],
       [ True,  True,  True]])

In [141]:
np.count_nonzero(original_array)

5

In [142]:
#  Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4. 

x=np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [146]:
# Write a NumPy program to test whether specified values are present in an array. 
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 

5.12 in x


True

In [152]:
# Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded. 

np.linspace(0,1,10,endpoint=True)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [153]:
# Write a NumPy program to make an array immutable

original_array.flags.writeable == False

False

In [157]:
original_array[-1][-1] == 800

False

In [158]:
original_array

array([[ 0, 10, 20],
       [20, 30, 40]])

In [160]:
# Write a NumPy program to create an array with 10^3 elements. 

np.arange(1e3
         )

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [171]:
# Write a NumPy program to create and display every element of a NumPy array.

x = np.arange(12).reshape(3, 4)

print(x[:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [172]:
#  Write a NumPy program to create a 5x5x5 cube of 1's. 

np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [173]:
# Write a NumPy program to create an array of (3, 4) shapes, multiply every element value by 3 and display the result array.

original_array = np.arange(12).reshape(3,4)

In [174]:
original_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [175]:
original_array = original_array * 3

In [176]:
original_array

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [177]:
#  Write a NumPy program to combine a one and two dimensional array together and display their elements. 

In [178]:
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [184]:
# Write a NumPy program to create an array of zeros and three column types (integer, floating, and character).

x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data

In [185]:
print(x)

[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


In [191]:
# Write a NumPy program to create a function cube for all array elements.

original_array = np.array([1,2,3])
new_array = np.power(original_array,3
                    )


In [192]:
new_array

array([ 1,  8, 27], dtype=int32)

In [193]:
# Write a NumPy program to create an array of (3, 4) shapes and convert the array elements into smaller chunks.

x= np.arange(12).reshape(3, 4)

In [194]:
np.transpose(x)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [195]:
# Write a NumPy program to create a record array from a (flat) list of arrays.
# Sample arrays: [1,2,3,4], ['Red', 'Green', 'White', 'Orange'], [12.20,15,20,40]

a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

In [196]:
results = np.core.records.fromarrays([a1,a2,a3],names='a,b,c')


In [197]:
print(results)

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]


In [198]:
#  Write a NumPy program to convert a NumPy array into a Python list structure.
# Expected Output:

original_array = np.array([[0,1],[2,3],[4,5]])
original_array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [200]:
list = original_array.tolist()

In [201]:
print(list)

[[0, 1], [2, 3], [4, 5]]


In [202]:
# Write a NumPy program to access an array by column. 

original_array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [203]:
original_array[0]

array([0, 1])

In [204]:
# Write a NumPy program to convert a NumPy array of floating values to a numpy array of integer values.

x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
x

array([[12.  , 12.51],
       [ 2.34,  7.98],
       [25.23, 36.5 ]])

In [205]:
x.astype(dtype = np.int32)

array([[12, 12],
       [ 2,  7],
       [25, 36]])

In [206]:
# Write a NumPy program to display a NumPy array of floating values with precision.

x=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 

In [207]:
x

array([0.26153123, 0.52760141, 0.5718299 , 0.5927067 , 0.7831874 ,
       0.69746349, 0.35399976, 0.99469633, 0.0694458 , 0.54711478])

In [208]:
np.set_printoptions(precision=3)

In [209]:
x

array([0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069,
       0.547])

In [210]:
# Write a NumPy program to suppress the use of scientific notation for small numbers in a NumPy array. 

x=np.array([1.6e-10, 1.6, 1200, .235]) 

In [211]:
np.set_printoptions(suppress=True)

In [212]:
x

array([   0.   ,    1.6  , 1200.   ,    0.235])

In [217]:
# Write a NumPy program to add an extra column to a NumPy array.

array_1 = np.array([[10,20,30],[40,50,60]])
array_2 = np.array([[100],[200]])

In [218]:
array_1

array([[10, 20, 30],
       [40, 50, 60]])

In [219]:
array_2

array([[100],
       [200]])

In [221]:
np.append(array_1,array_2,1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [223]:
# Write a NumPy program to find distinct rows in a NumPy array.

x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])
print("Original array:")
print(x)

Original array:
[[20 20 20  0]
 [ 0 20 20 20]
 [ 0 20 20 20]
 [20 20 20  0]
 [10 20 20 20]]


In [224]:
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)

unique_result = x[idx]
print("Unique rows of the above array:")
print(unique_result)

Unique rows of the above array:
[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]


In [225]:
# Write a NumPy program to replace all elements of NumPy array that are greater than the specified array.
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)


Original array:
[[0.424 0.486 0.329]
 [0.744 0.582 0.382]
 [0.51  0.345 0.156]]


In [229]:
x[x>.5] = 0.5

In [230]:
x

array([[0.424, 0.486, 0.329],
       [0.5  , 0.5  , 0.382],
       [0.5  , 0.345, 0.156]])

In [233]:
#  Write a NumPy program to remove specific elements from a NumPy array

original_array = np.linspace(10,100,10)

In [234]:
original_array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [235]:
delete_index = [0,3,4]

In [236]:
np.delete(original_array,delete_index)

array([ 20.,  30.,  60.,  70.,  80.,  90., 100.])

In [237]:
#  Write a NumPy program to replace the negative values in a NumPy array with 0. 

original_array = np.array([-1,-4,0,2,3,4,5,-6])
original_array

array([-1, -4,  0,  2,  3,  4,  5, -6])

In [241]:
original_array[original_array[:] < 0] = 0

In [242]:
original_array

array([0, 0, 0, 2, 3, 4, 5, 0])

In [243]:
# Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values. 
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
x


array([[ 1.,  2.,  3.],
       [ 4.,  5., nan],
       [ 7.,  8.,  9.],
       [ 1.,  0.,  1.]])

In [244]:
x[~np.isnan(x).any(axis = 1)]

array([[1., 2., 3.],
       [7., 8., 9.],
       [1., 0., 1.]])

In [245]:
# Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])


In [246]:
a<100

array([ True, False, False, False, False])

array([False,  True,  True,  True,  True])

In [248]:
b[(100<a)&(a<110)]

array(['e', 'i'], dtype='<U1')

In [253]:
# Write a NumPy program to get the magnitude of a vector in NumPy. 

original_array = np.array([1,2,3,4,5])
original_array

array([1, 2, 3, 4, 5])

In [254]:
np.linalg.norm(original_array)

7.416198487095663

In [255]:
# Write a NumPy program to count the frequency of distinct values in a NumPy array.

a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )

In [257]:
unique_elements , count_numbers = np.unique(a,return_counts=True)

In [259]:
np.asarray((unique_elements,count_numbers))

array([[10, 20, 30, 40, 50],
       [ 3,  4,  2,  2,  1]], dtype=int64)

In [260]:
# Write a NumPy program to check whether the NumPy array is empty or not. 

x= np.array([2,2])
y = np.array([])

In [261]:
x.size

2

In [262]:
y.size

0

In [263]:
# Write a NumPy program to divide each row by a vector element

x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print("Original array:")
print(x)
v = np.array([20,30,40])
print("Vector:")

Original array:
[[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:


In [264]:
print(v)

[20 30 40]


In [266]:
x/v[:,None]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [267]:
#  Write a NumPy program to sum and compute the product of a numpy array of elements.

original_array = np.array([10,20,30])
original_array

array([10, 20, 30])

In [268]:
np.sum(original_array)

60

In [269]:
np.product(original_array)

6000

In [270]:
# Write a NumPy program to print the full NumPy array, without truncation.

import numpy as np
import sys
nums = np.arange(2000)
np.set_printoptions(threshold=sys.maxsize)
print(nums)


[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

In [271]:
# Write a NumPy program to create to concatenate two given arrays of shape (2, 2) and (2,1). 

nums1 = np.array([[4.5, 3.5],
                 [5.1, 2.3]])
nums2 = np.array([[1],
                  [2]])

In [272]:
nums1

array([[4.5, 3.5],
       [5.1, 2.3]])

In [273]:
nums2

array([[1],
       [2]])

In [275]:
np.concatenate((nums1,nums2),axis=1)

array([[4.5, 3.5, 1. ],
       [5.1, 2.3, 2. ]])

In [277]:
# Write a NumPy program to create a 12x12x4 array with random values and extract any array of shape(6,6,3) from the said array. 

nums = np.random.random((12,12,4))
nums[:6,:6,:]


array([[[0.01 , 0.431, 0.36 , 0.632],
        [0.181, 0.636, 0.28 , 0.375],
        [0.543, 0.141, 0.235, 0.658],
        [0.84 , 0.938, 0.207, 0.115],
        [0.73 , 0.654, 0.808, 0.092],
        [0.021, 0.564, 0.838, 0.639]],

       [[0.554, 0.603, 0.569, 0.851],
        [0.107, 0.072, 0.606, 0.01 ],
        [0.871, 0.896, 0.936, 0.577],
        [0.198, 0.392, 0.295, 0.854],
        [0.638, 0.629, 0.162, 0.139],
        [0.136, 0.362, 0.348, 0.862]],

       [[0.246, 0.822, 0.78 , 0.67 ],
        [0.64 , 0.513, 0.676, 0.587],
        [0.269, 0.735, 0.624, 0.755],
        [0.52 , 0.991, 0.741, 0.193],
        [0.56 , 0.768, 0.551, 0.392],
        [0.043, 0.517, 0.577, 0.566]],

       [[0.469, 0.61 , 0.241, 0.139],
        [0.811, 0.878, 0.376, 0.83 ],
        [0.792, 0.165, 0.051, 0.099],
        [0.506, 0.042, 0.351, 0.374],
        [0.467, 0.867, 0.748, 0.342],
        [0.454, 0.438, 0.162, 0.695]],

       [[0.777, 0.941, 0.561, 0.546],
        [0.962, 0.088, 0.096, 0.976],
    