In [62]:
import numpy as np


In [63]:
a= np.arange(10)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# Write a NumPy program to test whether none of the elements of a given array are zero

In [68]:
a[a[:] == 0]

array([0])

In [71]:
# Write a NumPy program to test if any of the elements of a given array are non-zero

a[a[:]!=0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number)
a[np.isinf(a)]

array([], dtype=int32)

In [79]:
#  Write a NumPy program to test elements-wise for positive or negative

a[a[:]>0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a[a[:]<0]

array([], dtype=int32)

In [82]:
a[np.isnan(a[:])]

array([], dtype=int32)

In [84]:
# Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.


numpy.ndarray

In [87]:
a[np.iscomplex(a)]

array([], dtype=int32)

In [88]:
a[np.isreal(a)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.isscalar(a)

False

In [90]:
# Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 

In [97]:
a = np.arange(100)
b = np.arange(100)

In [98]:
a[np.array_equal(a,b)]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [94]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [99]:
np.greater(a,b)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [100]:
np.greater_equal(a,b)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [101]:
np.less(a,b)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [102]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [103]:
array_test = np.array([1,7,13,105])

In [106]:
array_test.size * array_test.itemsize


16

In [107]:
# rite a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [108]:
array_zeros = np.zeros(shape=10)

In [109]:
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
array_ones = np.ones(shape=10)

In [112]:
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:

array_2 = np.full(shape=10,fill_value=5)
array_2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [114]:
# Write a NumPy program to create an array of integers from 30 to 70.

array_test = np.arange(10,71)

In [115]:
array_test

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70])

In [116]:
# Write a NumPy program to create an array of all even integers from 30 to 70.

array_test = np.arange(10,71) 

In [118]:
array_test[array_test[:]%2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70])

In [120]:
#  Write a NumPy program to create a 3x3 identity matrix.

matrix_A = np.eye(3, dtype=int)

matrix_A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [124]:
# Write a NumPy program to generate a random number between 0 and 1

rand_num = np.random.normal(0,1,1)
rand_num

array([0.32805533])

In [125]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
rand_num = np.random.normal(0,1,15)
rand_num

array([ 0.68811125, -0.33312651, -0.20418272, -1.05513577, -1.28643032,
        1.29387588,  0.40272445, -0.81757761, -0.61553022, -0.14060825,
       -0.32924618, -0.33354784,  1.3652885 ,  0.21274614, -1.16695408])

In [127]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

a = np.arange(15,55)

a



array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [128]:
a[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [136]:
# Write a NumPy program to create a 3X4 array and iterate over it

a= np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:

# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [138]:
v = np.linspace(10, 49, 5)



In [139]:
v

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [146]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
v = np.arange(0, 20)
v[(v>=9)&(v<=15)]*=-1
v

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19])

In [147]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

a= np.linspace(0,10,5)

In [148]:
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [151]:

b= np.linspace(0,10,5)
b

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [152]:
a*b

array([  0.  ,   6.25,  25.  ,  56.25, 100.  ])

In [156]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

matrix_A = np.arange(10,22)

In [159]:
matrix_A = matrix_A.reshape((3,4))
matrix_A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [163]:
# Write a NumPy program to find the number of rows and columns in a given matrix

i,j = matrix_A.shape
print("Number of rows is {}".format(i))
print("Number of columns is {}".format(j))

Number of rows is 3
Number of columns is 4


In [164]:
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

matrix_a_10 = np.eye(10)

In [165]:
matrix_a_10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [166]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

matrix_a = np.diag([1,2,3,4,5])
matrix_a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [171]:
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 

x= np.zeros((4,4))
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [179]:
# 31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values

a= np.random.random((3,3,3))

In [180]:
# Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array. 

np.sum(a,axis=0)
np.sum(a)
np.sum(a,axis=1)

array([[1.35587115, 2.6703735 , 1.99894465],
       [1.85401356, 1.7107052 , 1.82346017],
       [1.34003589, 1.53674621, 1.60613912]])

In [182]:
x = np.array([4, 5])
y = np.array([7, 10])

np.dot(x,y)

78

In [183]:
# Write a NumPy program to add a vector to each row of a given matrix.

x 

array([4, 5])

In [185]:
a

array([[[0.70103799, 0.84601107, 0.6900062 ],
        [0.35380679, 0.88270512, 0.96982848],
        [0.30102636, 0.94165731, 0.33910998]],

       [[0.0591079 , 0.18160461, 0.48154218],
        [0.97476068, 0.883821  , 0.48427585],
        [0.82014498, 0.64527959, 0.85764215]],

       [[0.29306186, 0.81517459, 0.63306763],
        [0.07391555, 0.12178304, 0.77788118],
        [0.97305848, 0.59978858, 0.19519032]]])

In [187]:
np.sum(a,x,axis=0)

TypeError: sum() got multiple values for argument 'axis'

In [190]:
# Write a NumPy program to find missing data in a given array
matrix_A = np.array([1,2,np.nan,4,5,np.nan])

In [193]:
matrix_A[np.isnan(matrix_A)]

array([nan, nan])

In [194]:
# Write a NumPy program to check whether two arrays are equal (element wise) or not
a
b


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [195]:
b


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [197]:
a

array([[[0.70103799, 0.84601107, 0.6900062 ],
        [0.35380679, 0.88270512, 0.96982848],
        [0.30102636, 0.94165731, 0.33910998]],

       [[0.0591079 , 0.18160461, 0.48154218],
        [0.97476068, 0.883821  , 0.48427585],
        [0.82014498, 0.64527959, 0.85764215]],

       [[0.29306186, 0.81517459, 0.63306763],
        [0.07391555, 0.12178304, 0.77788118],
        [0.97305848, 0.59978858, 0.19519032]]])

In [199]:
np.array_equal(a,b)

False

In [200]:
# Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1

In [202]:
a=np.random.random((8,5))

In [203]:
a

array([[0.00561802, 0.24980883, 0.60095171, 0.85560066, 0.3993979 ],
       [0.99744525, 0.28796   , 0.39894857, 0.00887479, 0.05337961],
       [0.31065411, 0.60983923, 0.01241756, 0.83077944, 0.87118636],
       [0.81794093, 0.2638863 , 0.04874494, 0.36496758, 0.27260092],
       [0.74214115, 0.19147343, 0.06796921, 0.80253728, 0.0499572 ],
       [0.90843013, 0.2491648 , 0.38037605, 0.8541555 , 0.73144404],
       [0.3308208 , 0.23215826, 0.27188095, 0.60558426, 0.0860778 ],
       [0.10843256, 0.33834805, 0.38178347, 0.35033475, 0.02622281]])

In [204]:
# Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

In [206]:
a=np.random.random((4,4))
a

array([[0.6975924 , 0.83927069, 0.87785288, 0.06196464],
       [0.73351017, 0.53716904, 0.36397308, 0.95574618],
       [0.93316952, 0.49813628, 0.76914337, 0.94740318],
       [0.57588885, 0.6793372 , 0.18742575, 0.43410484]])

In [210]:
a[a[0,:] == a[3,:] & a[3,:] == a[0,:]]

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''