In [2]:
import numpy as np

In [37]:
# list of list
list_a = [[1,2,3],[4,5,6]]

In [38]:
len(list_a)


2

In [39]:
array_a = np.array(list_a)


In [40]:
type(array_a)

numpy.ndarray

In [41]:
type(list_a)

list

In [42]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [43]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [45]:
array_a.shape

(2, 3)

In [17]:
# list has no seperate shape property

numpy.ndarray

In [47]:
# number of individual elements in a nested list
len(list_a[1])


3

In [49]:
len(list_a[0])

3

In [50]:
# array work element wise but not list

In [53]:
list_b = list_a[0]+list_a[1]
array_b = array_a[0]+array_a[1]

In [54]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [56]:
print(array_b)

[5 7 9]
