In [85]:
import numpy as np

In [86]:
# assigning values to an array
array_a = np.array([[1,2,3],[4,5,6]])

In [88]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [89]:
array_a[0,2] = 9

In [91]:
print(array_a)

[[1 2 9]
 [4 5 6]]


In [92]:
array_a[0] = 9

In [94]:
print(array_a)

[[9 9 9]
 [4 5 6]]


In [96]:
array_a[:,0] = 9



In [97]:
print(array_a)

[[9 9 9]
 [9 5 6]]


In [98]:
# passing list to an array
list_a = [8,7,8]
array_a[0] = list_a

In [99]:
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [100]:
type(array_a)

numpy.ndarray

In [101]:
array_a = 9


In [102]:
print(array_a)

9


In [103]:
array_a

9

In [104]:
array_a = np.array([[1,2,3],[4,5,6]])