In [161]:
import numpy as np

In [162]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [163]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [164]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [165]:
### 2. Display the first element (not necessarily individual element) for each of the 3 arrays we defined above.

In [167]:
array_1D[0]

10

In [171]:
array_2D[0]

array([20, 30, 40, 50, 60])

In [173]:
array_3D[0][0]

array([1, 2, 3, 4, 5])

In [174]:
### 3. Call the first individual element of the each of the 3 arrays. 

In [177]:
array_1D[0]

10

In [178]:
array_2D[0][0]

20

In [179]:
array_3D[0][0][0]

1

In [180]:
### 4. Uses negative indices to display the last element of each array.

In [182]:
array_1D[-1]

14

In [185]:
array_2D[-1][-1]

55

In [186]:
array_3D[-1][-1][-1]

5

In [187]:
### 5. Set the penultimate (second-to-last) <i> individual </i> element of each array equal to 10. Then display the variables to check your work.

In [191]:
array_1D[-2] = 10

In [193]:
array_1D

array([10, 11, 12, 10, 14])

In [195]:
array_2D[-1][-2]  = 10

In [196]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [198]:
array_3D[-1][-1][-2]  = 10

In [200]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 10,  5]]])

In [201]:
### 6. Set the last column of the 2-D array to 100. Then display the variables to check your work. 

In [206]:
array_2D[:,4] = 100

In [207]:
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

In [208]:
### 7. Set all the values of the 3-D array to 1000. Then display the variables to check your work. 

In [209]:
array_3D[:,:]= 100

In [210]:
array_3D

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [211]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [212]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [213]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [216]:
### 9. Add 2 to every element of the 3 arrays without overwriting their values.
array_3D + 2

array([[[ 3,  4,  5,  6,  7],
        [13, 23, 33, 43, 53]],

       [[13, 14, 15, 16, 17],
        [53, 54, 55, 56,  7]]])

In [217]:
### 10. Multiply the values of each array by 100 without overwriting their values.

In [219]:
array_1D * 100

array([1000, 1100, 1200, 1300, 1400])

In [220]:
array_2D*100

array([[2000, 3000, 4000, 5000, 6000],
       [4300, 5400, 6500, 7600, 8700],
       [1100, 2200, 3300, 4400, 5500]])

In [222]:
array_3D * 100

array([[[ 100,  200,  300,  400,  500],
        [1100, 2100, 3100, 4100, 5100]],

       [[1100, 1200, 1300, 1400, 1500],
        [5100, 5200, 5300, 5400,  500]]])

In [223]:
### 11. Add up <i>array_1D</i> and the first row of <i>array_2D</i>
array_1D + array_2D[0]

array([30, 41, 52, 63, 74])

In [224]:
### 12. Find the product of <i>array_1D</i> and the first row of <i>array_2D</i>

In [225]:
array_1D * array_2D[0]

array([200, 330, 480, 650, 840])

In [226]:
### 13. Find the product  of the first row of <i>array_2D</i> and the first row of the first array of <i> array_3D </i>

In [230]:
array_2D[0] * array_3D[0][0]

array([ 20,  60, 120, 200, 300])

In [235]:
array_1D = np.array([10,11,12,13,14], dtype = np.float32)
array_1D

array([10., 11., 12., 13., 14.], dtype=float32)

In [236]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]],dtype = np.float32)
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [237]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]], dtype=float32)

In [238]:
### 18. Use broadcasting to subtract  <i>array_1D</i> from every row of <i> array_2D </i> 

In [239]:
array_2D[:,:]- array_1D

array([[10., 19., 28., 37., 46.],
       [33., 43., 53., 63., 73.],
       [ 1., 11., 21., 31., 41.]], dtype=float32)

In [240]:
### 19. Use broadcasting to divide all rows of <i>array_3D</i> by <i> array_1D </i> 

In [242]:
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]], dtype=float32)

In [244]:
array_3D[:,:,:] / array_1D

array([[[0.1       , 0.18181819, 0.25      , 0.30769232, 0.35714287],
        [1.1       , 1.9090909 , 2.5833333 , 3.1538463 , 3.642857  ]],

       [[1.1       , 1.0909091 , 1.0833334 , 1.0769231 , 1.0714285 ],
        [5.1       , 4.7272725 , 4.4166665 , 4.1538463 , 0.35714287]]],
      dtype=float32)

In [249]:
### 19. Use broadcasting to find the product of all rows of <i>array_3D</i>  and the last row of <i> array_2D </i> 

In [250]:
array_2D[-1]

array([11., 22., 33., 44., 55.], dtype=float32)

In [252]:
array_3D[:,:,:] * array_2D[-1]

array([[[  11.,   44.,   99.,  176.,  275.],
        [ 121.,  462., 1023., 1804., 2805.]],

       [[ 121.,  264.,  429.,  616.,  825.],
        [ 561., 1144., 1749., 2376.,  275.]]], dtype=float32)