In [2]:
import numpy as np

In [68]:
# indexing

array_a = np.array([[1,2,3],[4,5,6]])

In [69]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [71]:
# specific values

first_element = array_a[0]
print(first_element)

[1 2 3]


In [72]:
first_first = array_a[0][0]
print(first_first)

1


In [73]:
array_a[1]

array([4, 5, 6])

In [75]:
second_first = array_a[1][0]
print(second_first)

4


In [77]:
second_second = array_a[1][1]
print(second_second)

5


In [78]:
# second first
array_a[1,0]

4

In [79]:
# all columns 
array_a[:,0]

array([1, 4])

In [81]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [84]:
array_a[-1][-1]

6