In [2]:
import numpy as np

In [4]:
#  ndarray
# a special datatype in python
# element wise properties

In [7]:
# declare an nd array

array_a = np.array([1,2,3])


In [8]:
array_a

array([1, 2, 3])

In [10]:
type(array_a)

numpy.ndarray

In [11]:
# nd array is object of array(name of function)

In [13]:
array_a.shape

(3,)

In [15]:
array_b = np.array([[1,2,3],[4,5,6]])

In [16]:
array_b.shape

(2, 3)

In [17]:
type(array_b)

numpy.ndarray

In [19]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [20]:
print(array_a)

[1 2 3]


In [23]:
array_c = np.array(14)

In [25]:
type(array_c)

numpy.ndarray

In [27]:
array_c.shape

()

In [29]:
array_d = np.array([15])

In [31]:
type(array_d)

numpy.ndarray

In [33]:
print(array_d)

[15]


In [34]:
array_d.shape

(1,)