In [253]:
import numpy as np

In [254]:
# Broadcasting

In [255]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [256]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [259]:
matrix_c = np.array([[1,2,3],[4,5,6]])

In [260]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [261]:
# # uinversal functions
# add
# subtract
# divide 
# multiply

In [262]:
type(matrix_c)

numpy.ndarray

In [263]:
# broadcasting 
# to control elementwisr operations but have elements of different sizes, shapes and dimensions

In [265]:
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [266]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

In [267]:
# broadcasting rules:
#     1. arrays have same shape
#     2. The arrays have same number of dimensions, and the length of each dimensio

In [268]:
# Type casting

In [271]:
np.add(array_b,matrix_c, dtype = np.float32)

array([[2., 3., 4.],
       [6., 7., 8.]], dtype=float32)

In [272]:
# running over an axis

In [275]:
# axis = 0 mean for each column
np.mean(matrix_c, axis=0)

array([2.5, 3.5, 4.5])

In [276]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [277]:
# axis =1 mean for each row
np.mean(matrix_c, axis=1)

array([2., 5.])