In [126]:
import numpy as np

In [127]:
# numpy datatypes

In [128]:
array_a = np.array([[1,2,3],[4,5,6]])

In [129]:
array_a


array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = 'float32')

In [134]:
type(array_a
    )

numpy.ndarray

In [137]:
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [139]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float32)

In [140]:
array_a.shape


(2, 3)

In [141]:
# complexnumbers

In [143]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)

In [144]:
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [145]:
# booleans 

In [148]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = 'bool')

In [150]:
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [152]:
# Text


In [157]:
array_a = np.array([[1,2,3],[4,5,6]], dtype=str)


In [159]:
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')