In [540]:
import numpy as np

In [541]:
# Application of random generators

In [543]:
array_rg = gen(pcg(365))

array_column_1 = array_rg.normal(loc = 2, scale = 3, size =(1000))
array_column_2 = array_rg.normal(loc = 7, scale = 2, size =(1000))
array_column_3 = array_rg.logistic(loc = 11, scale = 3, size =(1000))
array_column_4 = array_rg.exponential(scale = 4, size =(1000))
array_column_5 = array_rg.geometric(p= 0.7 ,size =(1000))

In [544]:
# create a bigger array with all of them in it
# export that array into csv file

array([ 1.59077303e+00,  2.28243293e+00,  1.81098674e+00,  5.16174922e+00,
       -6.00453946e-02,  4.72334808e-01, -3.99857800e-01,  4.19125476e+00,
        2.26476316e+00, -4.35327281e+00,  3.96580322e+00,  5.57149638e-01,
        3.44265788e-01,  2.42640151e-01, -9.47736887e-01,  5.37134498e+00,
       -1.92952948e+00,  1.85888679e+00,  4.86581600e+00,  2.78215234e+00,
        1.39928997e+00, -2.50517452e+00, -2.47874891e+00,  4.89605251e+00,
        5.56083900e+00, -2.81967317e-01,  6.44475073e+00,  2.03600775e+00,
        1.79459124e+00,  2.75904992e+00,  4.20776356e-01,  4.38839327e+00,
        2.84610264e+00,  7.40714024e+00,  4.81796350e+00,  3.89201495e-01,
        1.21046934e+00, -3.33169105e+00,  5.44700039e+00, -4.62201744e+00,
        6.62350324e+00,  4.62520385e-01, -4.43693690e+00,  7.96636020e+00,
        2.96626720e+00, -1.79544851e+00,  1.18143899e+01,  7.35951479e+00,
        1.39298976e+00,  2.61282402e+00,  3.76490418e+00,  3.29191506e+00,
        3.28615584e+00,  

In [548]:
random_test_data = np.array([array_column_1,array_column_2,array_column_3,array_column_4,array_column_5]).transpose()

In [549]:
random_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [550]:
random_test_data.shape

(1000, 5)

In [551]:
# save dataset to csv file

In [555]:
np.savetxt("Random-Test-from-numpy.csv",random_test_data,fmt = "%s", delimiter=',')

In [557]:
# load the saved file

In [560]:
np.genfromtxt("Random-Test-from-numpy.csv", delimiter = ',')

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])