In [483]:
import numpy as np

In [485]:
# # np.arange()

# arange = array range

# creates a sequence og consecutive values

In [487]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [488]:
array_range = np.arange(30)

In [489]:
array_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [491]:
array_range = np.arange(start = 0, stop =30)
array_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [494]:
array_range = np.arange(start = 0, stop =30,step = 2.5, dtype = np.float64)
array_range

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [496]:
array_range = np.arange(start = 0, stop =30,step = 2.5, dtype = np.int32)
array_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])