In [457]:
import numpy as np

In [458]:
# generating data with numpy

In [462]:
# np.empty()
array_empty = np.empty(shape = (2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [466]:
# np.zeros()
array_0s = np.zeros(shape = (2,3),dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [467]:
# np.ones

array_1s = np.ones(shape=(2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [470]:
# np.full()

array_full = np.full(shape=(2,3),fill_value=2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])