In [497]:
import numpy as np

In [513]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [514]:
array_rg = gen(pcg(seed = 365))

In [518]:
array_rg.normal(size = (7,7))

array([[-0.06300442,  1.05391641, -0.6866818 , -0.50922173, -0.7999526 ,
         0.73041825,  0.08825439],
       [-2.1177576 ,  0.65526774, -0.48095012, -0.5519114 , -0.58578662,
        -0.98257896,  1.12378166],
       [-1.30984316, -0.04703774,  0.955272  ,  0.26071745, -0.20023668,
        -1.50172484, -1.4929163 ],
       [ 0.96535084,  1.18694633, -0.76065577,  1.48158358,  0.01200258,
        -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117,
        -0.53693283, -0.26317689],
       [-1.77723035,  1.14900013, -2.20733915,  1.54116775, -0.5124932 ,
        -2.14564563,  1.98878673],
       [ 0.32208907, -1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,
         0.20427467,  0.58830139]])

In [520]:
array_rg.integers(low = 10, high =100, size =(5,5))

array([[43, 48, 58, 22, 83],
       [67, 16, 34, 94, 13],
       [53, 60, 93, 11, 30],
       [35, 68, 70, 12, 51],
       [97, 83, 41, 96, 16]], dtype=int64)

In [521]:
array_rg = gen(pcg(seed = 365))
array_rg.random( size =(5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [522]:
# numpy.choice()
# simulates the idea of making an arbitary choice out of a given sequence

In [526]:
array_rg = gen(pcg(seed = 365))
array_rg.choice([1,2,3,4,5]
                , size =(5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [527]:
array_rg = gen(pcg(seed = 365))
array_rg.choice([1,2,3,4,5],p=[0.1,0.1,0.1,0.1,0.6], size =(5,5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])