In [471]:
import numpy as np

In [472]:
# like functions


In [473]:
matrix_a = np.array([[1,0,9,2,2],[3,3,3,5,4],[1,2,3,4,1]])

In [475]:
matrix_a

array([[1, 0, 9, 2, 2],
       [3, 3, 3, 5, 4],
       [1, 2, 3, 4, 1]])

In [476]:
array_empty_like = np.empty_like(matrix_a)

In [477]:
array_empty_like

array([[   0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0],
       [1628,    0,    0,  458,    0]])

In [478]:
array_empty_like.shape

(3, 5)

In [479]:
# zeroslike
array_zero_like = np.zeros_like(matrix_a)

In [480]:
array_zero_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [481]:
#ones like
array_one_like = np.ones_like(matrix_a)

In [482]:
array_one_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])