In [528]:
import numpy as np

In [530]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [534]:
# Poision distribution
array_rg = gen(pcg(seed = 365))
array_rg.poisson(size=(5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]], dtype=int64)

In [535]:
# Poision distribution
array_rg = gen(pcg(seed = 365))
array_rg.poisson(size=(5,5),lam = 10)

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [536]:
# Boinomial Distribution
# measures how many times a certain outcome can appear over a series of trials , where 
# there are only 2 possible outcomes

In [537]:
array_rg = gen(pcg(seed = 365))
array_rg.binomial(size=(5,5),n=100, p= 0.4)

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]], dtype=int64)

In [539]:
# Logistic distribution
# each element is possible outcome of a logistic distribution with loc = 9 and scale = 1.2

array_rg = gen(pcg(seed = 365))
array_rg.logistic(size=(5,5),scale = 1.2, loc = 9)

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])