In [497]:
import numpy as np

In [498]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [499]:
# the generator function takes a bit generator as an input and creates generator object

In [501]:
array_rg = gen(pcg())
array_rg.normal(size = (5,5))

array([[ 0.18216682,  1.31046432,  0.89681973, -0.9451938 ,  1.07423717],
       [-0.49836978, -0.73463532,  2.24520327, -0.8438425 ,  0.43726786],
       [ 0.47552842,  1.78008906, -0.20446408,  0.12124379, -0.49638231],
       [ 0.2771853 ,  0.25181678,  0.15791141, -0.26163267, -0.9779416 ],
       [-1.65965578, -0.63694472, -0.93196798, -0.67043038, -2.11683345]])

In [502]:
# every time we call the method, the generator randomly selects a seed
# seed is a set of starting parameters for the algorithm

In [507]:
array_rg = gen(pcg(seed = 365))
array_rg.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [512]:
array_rg.normal(size = (5,5))

array([[-0.25906657, -0.16532638, -0.47735775, -0.52855221,  1.70374643],
       [-0.24469883, -0.14733608, -0.4081149 ,  0.85591897,  0.2208273 ],
       [-0.50401804, -0.31628129,  0.37721236,  0.72377218, -1.05689925],
       [-1.0395866 ,  0.39665421, -0.50851684, -0.38667483, -0.28611018],
       [ 0.03041171, -0.86403978,  0.62177882, -0.85974799, -0.16177904]])